### ISSUE TITLE
AMD-Documentar códigos de error cuali y quantitativas

### ISSUE THREAD

**Issue by alfredomesalles** [FranGomezVenegas/LP#143]

**Comment by FranGomezVenegas** [comment]
### **

- Quantitative Rules Errores (Numéricas)

**
    enum quantitativeRulesErrors{        
        MIN_OR_MAX_MANDATORY("MinAndMaxSpecOneOfBothMandatory"),         
        MINSPEC_MAXSPEC_MINSPEC_GREATEROREQUALTO_MAXSPEC("specLimits_quantitativeMinSpecMaxSpec_MinSpecGreaterOrEqualToMaxSpec"),
        
        MINCONTROLPRESENT_MINSPECMANDATORY("specLimits_MinControlPresent_MinSpecMandatory"), 
        MAXCONTROLPRESENT_MAXSPECMANDATORY("specLimits_MaxControlPresent_MaxSpecMandatory"),
        
        MINCONTROL_GREATEROREQUALTO_MAXCONTROL("specLimits_minControlGreaterOrEqualToMaxControl"),
        MINCONTROL_GREATEROREQUALTO_MAXSPEC("specLimits_minControlGreaterOrEqualToMaxSpec"),
        MAXCONTROL_LESSEQUALTO_MINSPEC("specLimits_maxControlLessThanOrEqualToMinSpec"),
        MINCONTROL_LESSEQUALTO_MINSPEC("specLimits_minControlLessThanOrEqualToMinSpec"),
        MAXCONTROL_GREATEROREQUALTO_MAXSPEC("specLimits_MaxControlGreaterThanOrEqualToMaxSpec"),
        MINCONTROL_MAXCONTROL_NOTLOGIC("specLimits_MinControlAndMaxControlOutOfLogicControl"),

### **

- Qualitative Rules Error (Texto)

**
    enum qualitativeRulesErrors{
        RULE_ARG_IS_MANDATORY("specLimits_ruleMandatoryArgumentNull"), TEXT_SPEC_ARG_IS_MANDATORY("specLimits_textSpecMandatoryArgumentNull"),
        QUALITATIVE_RULE_NOT_RECOGNIZED("specLimits_qualitativeRuleNotRecognized"), SEPARATOR_ARG_IS_MANDATORY("specLimits_separatorMandatoryArgumentNull"),
