### ISSUE TITLE
MOD3. IDENTIF. MICROORGAS--> revisar cómo poder agragar un microorg. que no sale en la lista "oficial". = PRP1. sin perder el control sobre el formato del nombre por parte de supervisión, que se tenga la posibilida de contabilizar.

### ISSUE THREAD

**Issue by FranGomezVenegas** [FranGomezVenegas/LP#168]

**Comment by FranGomezVenegas** [comment]
Se pueden agregar varias modalidades.
1) insertarlos en una tabla que permita al admin decidir cuáles agregar a la tabla oficial.
2) agregarlos a la tabla oficial directamente.
3) lo actual, no se añade a la tabla oficial ni se notifica al admin.
4) mandar un mail o request para informar de que se detecta un nuevo microorg que no está en la lista

**Comment by cyberflor** [comment]
no está acabada de definir esta manera
