### ISSUE TITLE
WH - diferenciar los colores de la tabla resumen de la tabla de pruebas

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#192]
poner la tabla resumen de otro color o el encabezado de la tabla de pruebas de otro color, pero que se puedan diferenciar la una de la otraY/o añadir un espacio separador

**Comment by FranGomezVenegas** [comment]
Añadido un espacio entre tablas y creado un css para la tabla summary a parte para así poder definir el aspecto de una tabla y de la otra por separado
