### ISSUE TITLE
Paso 31: se añade la lista de los microbitos entera, SOLUCION: solo añadir el micro seleccionado . y firmar el audit, tien un comportamiento difente en cada firma, SOLUCION: unificar comportamiento (ANTIC NOM: No refresca la tabla principal, refresco manual)

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#223]
En el audit, al paper-dialog se le añaden las propiedades always-on-top no-cancel-on-outside-click, esto no permite cerrar la pantalla de auditoria pulsando fuera del dialogo, la unica manera de cerrarla es pulscando tecla Escape o el botón. Prueba y dime qué tal va ahora

**Comment by cyberflor** [comment]
no puedo verificar correctamente si no puedo pasar una nueva muestra desde la etapa anterior, esto depende de la incidencia #339

**Comment by FranGomezVenegas** [comment]
Prueba pq 339 debe ser verificada pues ya funciona.

**Comment by cyberflor** [comment]
1. Cuando seselecciona un microorganismo de la lista y se hace click en añadir, la tabla refresca automáticamente pero añade toda la lista de micoorganismos.

2. El comportamiento de la firma es raro:
        -  en la primera da error, pero asimila la firma (pq es correcta)
        - después hay que ir haciendo clic en el aceptar
        - pero después acepta el enter cuando se firma.

**Comment by cyberflor** [comment]
verificado, sigue sin funcionar correctamente: he pasado las muestras 266 y 268 se les ha adjudicado dde forma automática Actinobacilus, e.coli, coccus
