### ISSUE TITLE
Paso 19: MEJORA La configuraría la pestaña "Personal" como la pestaña "Buscador" . Al abrir que salgan las 3 pestañas relacionadas con personal.

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#231]

**Comment by cyberflor** [comment]
Quitar el "seprador" con etiqueta PERSONAL y dejar solamente las 3 pantallas que van después y tienen contenido: - Muestreo - Personal, Lectura Placas- Personal, Identificación microorganismos- Personal

**Comment by FranGomezVenegas** [comment]
Creado el type icons-group
https://stackoverflow.com/questions/68277351/redux-dev-tool-distinguish-between-modes
