### ISSUE TITLE
Paso 8:  MEJORA -En vez de aparece icono con imagen del usuario aparece un cuadro negro junto a las palabras "Avatar" (imgaen adjunta en excel)

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#259]

**Comment by FranGomezVenegas** [comment]
Cierto, en verdad esta es una de las 'soluciones no consolidadas'. Ese avatar es el icono para poder abrir los PNTs asociados a este punto del proceso. No sé si está bien ahí o mejor si fuese un icono al lado del nombre del punto del proceso, en el árbol de procesos y que al pulsarlo se abran los PNTs de ese punto del proceso. 
En favor del 'avatar', la pantalla tiene más especio. En contra, que debes abrir la pantalla para ver 'el avatar'. Tenemos que tomar una decisión de qué camino tomar y entonces asegurar que funcione.

**Comment by cyberflor** [comment]
Entonces, es un elemento repetido? Si es el mismo que el grande que sale por encima de la lista de procesos, no debería estar lleva a la confusión. Con solo un elemento suficiente. Creo que sería mejor una tabla/lista de los PNT's que no un icono. 

El caso es que ese avatar se repite en todas las pantallas, pero si está fuera no debería estar en cada pantalla también. Quitarlo sería lo mejor.
