### ISSUE TITLE
Paso 14: se puede adaptar las  columnas, pero debería de haber un bloqueante para que no desaparezca del todo, que se ve al menos una letra de la columna .

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#286]

**Comment by cyberflor** [comment]
duda: el la columna creado no se puede hacer que salga el nombre del usuario? o siempre será un código? o es personalizable?

**Comment by cyberflor** [comment]
la columna cerrado por, creo que ya no es necesaria porque no salen los lotes cerrados en la tabla en esta pantalla.

**Comment by FranGomezVenegas** [comment]
Conseguido, he encontrado que el min-width estaba en 10px, lo he subido a 25px. Además lo he convertido a vw (1.627vw) para hacerlo responsive.

**Comment by cyberflor** [comment]
comportamiento conseguido, las columnas no desaparecen de fomna completa.
