### ISSUE TITLE
Paso 7: 2º clic botón reflresh - NO SE INFORMA si se ha hecho bien o no DEBERIA SALIR UN POPUP AZUL "actualizado"  y si hay algún cambio que informe así "Actualizado: 21/04/2020 suspendido muestreo  E01" (Mirar comentario). Esta petición va a ser rechazada

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#296]
Los botones Refrescar no van a tener nunca notificación porque no son acciones. Se notifica sobre acciones que realizan cambios, no acciones de refrescar pantallas sino tendríamos muchas notificaciones y eso no es viable, el panel es para que el usuario no vaya a realizar una misma acción dos veces por error y para saber qué acciones ya ha realizado durante la sesión, acciones=tareas

**Comment by FranGomezVenegas** [comment]
La verdad? No entiendo de qué se trata ¿me puedes hacer una demo?
