### ISSUE TITLE
Paso 8: la tabla debaJo del calendario debería llevar título. De hecho se debería poner título a las tablas en todas las pantallas (LISTA EN COMENTARIO)

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#298]

**Comment by cyberflor** [comment]
lista pestañas que tienen tablas  y deben llevar título:

- INCUBACIÓN (3)
- PROGRAMAS CALENDARIO CONFIG (1)

**Comment by FranGomezVenegas** [comment]
Hecho, le he puesto un color de texto a las tablas de las muestras y otro al de tandas, el que más te guste! :)

**Comment by cyberflor** [comment]
Falta la tabla de :
- Progrmas -> Calendario config
