### ISSUE TITLE
Paso 8: 2º se minimiza la última columna al máximo. - c.fallo deja texto fuera de la table SOLUCIÓN: PONER UN MÁXIMO DE MINIMIZACIÓN DE COLUMNAS y quitar check de la tabla (LISTA EN COMENTARIO) 

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#299]

**Comment by cyberflor** [comment]
Nombre de pestañas con tablas y que se debería aplicar un tope de minimización de columnas. También quitar el check de las tablas 

- Muestreo de muestras (1)
- Incubación (3)
- Lectura de placas (1)
- Identificación microorganismos (1)
- Personal - muestreo (1)
- Personal - lectura de placas (1) --> hay demasiada separación entre columnas, la config inicia deberia se porde ver todas las columnas a la vez
- Personal - microorganismos (1)  ---> revisar la columna estado no es ajustable 
- Programas - calendario config (1) 
- Programas - puntos de muestreo (1)
- Programas - puntos de muestreo mapa (1)
- Programas - acciones correctivas (1)

**Comment by FranGomezVenegas** [comment]
He tenido que crear la pregunta en el foro de vaadin porque el componente no tiene más que las propiedades width y resizable (esta es la que permite cambiar el tamaño de la columna), pero no hay ni min-width ni max-width, a ver qué responden/sugieren.

https://vaadin.com/forum/thread/18233827

**Comment by cyberflor** [comment]
Paso esto por aquí, para el tema de las tablas: https://www.youtube.com/watch?v=Q-foTLlevt4

Este artículo contiene las dos cosas, ajuste tamaño y menú desplegable aunque sea para seleccionar columnas nos ayudaría a resolver la incidencia de redimensionar
https://aukera.es/blog/tabla-html-responsive/

**Comment by cyberflor** [comment]
no se ha quitado el check de las tablas, parece funcionar correctamente ahora pero es molesto por el desajuste de resolución. Pero como la incidencia principal es sobre el comportamiento de la última columna, y esta ya no deja texto fuera tanto si se minimiza como si se mazimiza. Así queda cerrada la incidencia.
