### ISSUE TITLE
Paso 17 y 18: 6ºsale un pop-up azul se ha registrado la muestra correctamente "Registrada muestra 869 correctamente."  encuentro a falta el nombre del programa con el que se ha registrado

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#306]

**Comment by FranGomezVenegas** [comment]
No es fácil de resolver porque el mensaje es genérico de registrar muestras, no solo para monitoreo, y en otros módulos no se usa el concepto de programa. Se revisará en el futuro pero por ahora se archiva.

**Comment by FranGomezVenegas** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/26067165/150025273-79966a52-4d7a-4d0c-8538-810def26d2ae.png">
