### ISSUE TITLE
Paso 20: Confirmo funcionamiento correcto de la tabla de puntos de muestreo porque al no estar activos los puntos en el mapa ,  no permite hacer ninguna acción. Aunque puede que sea mejor añadir un mensaje de aviso que diga "no hay puntos activos" al hacer clic en el mapa.

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#307]

**Comment by FranGomezVenegas** [comment]
Lo que pasa aquí es que el primer programa (que es el que usamos para las pruebas) tiene todos los puntos pero no sus ubicaciones en el mapa, por eso esta pestaña no es 'compatible' con este programa. 
El segundo programa si tiene las ubicaciones en el mapa, con lo cual esta pestaña si es compatible, pero el diálogo de registrar muestras no es compatible con este programa ... jajajaja, toca alinear ambos programas para 'su deficiencia' particular ...

**Comment by FranGomezVenegas** [comment]
Voy a crear un campo en base de datos para cada programa donde se especifique los campos del formulario de muestras que le aplican ... es que el formulario actual es el que usa una empresa real ... pero si otra empresa quiere otros campos pues también debe ser posible ... la idea es asignar un formulario por cada programa ...

**Comment by cyberflor** [comment]
No se puede verificar porque no tengo activa la pestaña programas, este punto corresponde a la subpestaña Mapa puntos de muestreo

**Comment by FranGomezVenegas** [comment]
Ya está funcional la pantalla de Programas.

**Comment by cyberflor** [comment]
ok! funciona, queda cerrada esta incidencia. Se añade nota de mejora: creo que se debería de añadir un titulito a los diálogos que pidan firma-e, para diferenciar cuando hay que insertar la contraseña o la firma
