### ISSUE TITLE
Paso 21: no se abre diálogo cuando se hace clic sobre el punto de muestreo y tampoco hay botón "nueva muestra"

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#308]

**Comment by cyberflor** [comment]
No se puede verificar porque no tengo activa la pestaña programas, este punto corresponde a la subpestaña Mapa puntos de muestreo

**Comment by FranGomezVenegas** [comment]
usa http://51.75.202.142:8888/uncompNew/index.html , aquí si funciona Programas

**Comment by cyberflor** [comment]
verificado en http://51.75.202.142:8888/trazit/index.html, funciona correctamente. cierro incidencia
