### ISSUE TITLE
Paso 24: El mensaje debería mostrar el número de la muestra a la que se ha aplicado la acción correctiva. Y me pregunto ¿a dónde van esas muestras?

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#310]
No lo había incorporado aún porque intenté mantener la grid 'lo más simple posible' hasta verificar que funcionaran ... y después añadirle este tipo de cosas ... ya lo añadí. Ahora debe verse así:
![image](https://user-images.githubusercontent.com/26067165/85850434-10f5f080-b7ad-11ea-8093-d8ea9542457b.png)

**Comment by cyberflor** [comment]
(PARA MI) volver a revisar--> 

em-demo-a.undefined.CORRECTIVE_ACTION_COMPLETE : API, Mensaje de Error: Firma electronica incorrecta, no coincide con la frase del Token.

[aunque la contraseña es correcta]

**Comment by cyberflor** [comment]
pestaña programas no funciona, ni en UncomNew ni en es6prodNew, esto se comprueba en la subpestaña acciones correctivas.

**Comment by FranGomezVenegas** [comment]
Ya si

**Comment by cyberflor** [comment]
molto bene! incidencia zanjada
