### ISSUE TITLE
ACTIVAR: - PNTS y FRIMA - RUTAS EN COMETARIO

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#312]
La firma no me funciona

**Comment by cyberflor** [comment]
- [FIRMA] LAUDF.001 > modules\em-demo-a\04-procedure\dialogs\em-demo-a-list-modal-sample-audit.js

- [PNT ] PPNTP.001 > app\01-main-views\sop\my-pending-sops.js
- [PNT ] PPNTPT.001 > app\01-main-views\sop\my-sops.js
- [PNT ]  IPNTA.001 > app\01-main-views\sop\pdf-link.js
- [PNT] PPNTPR.001 > app\01-main-views\sop\procedure-sops.js
- [PNT]  EPNTC.001 > app\01-main-views\sop\sop-iconandbadge.js
- [PNT] ENULL.001 > app\01-main-views\sop\sops-tree-pane.js

**Comment by FranGomezVenegas** [comment]
¿Ya lo tienes, no?

**Comment by cyberflor** [comment]
La firma Todavia no la he provado.

**Comment by cyberflor** [comment]
si me dice cuál me has puesto para ponder cambiarla y ver que funciona, la dejamos por cerrada. HE podido concluir acciones correctivas pero no puedo hacer cambio de contraseña
