### ISSUE TITLE
Paso 2:  sale una gráfica, que no sé ni a qué progrma se refiere y además demasiado pequeña. Solución-. hacer más grande la gráfica y de título el programa al que pertenece y la fecha

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#314]
Igual que #293. La gráfica ahora tiene titulo y debe ayudar a saber qué datos representa ...

**Comment by cyberflor** [comment]
sigue sin mostrarse claramente a qué programa pertenecen los datos que aparecen

**Comment by FranGomezVenegas** [comment]
Ahora las gráficas tienen el atributo para añadirle un título.
