### ISSUE TITLE
ACTIVAR: INCIDENCIAS

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#316]

**Comment by FranGomezVenegas** [comment]
Ahora ya tienes acceso a Incidencias con el botón en la parte superior derecha ¿es esto? Si es así, cierra esta incidencia jejejej que hay muchas abiertas :(

**Comment by cyberflor** [comment]
Si, ahora cierro esto..però recuerda de ir pasandolas pendiente de verificación?
