### ISSUE TITLE
Paso 3: no se abre el 1º SOP Name: DEMO - NO SE ABRE pop-up ERROR: "Este PNT no tiene PDF asociado";

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#318]

**Comment by FranGomezVenegas** [comment]
No se considera un error. El cliente puede decidir crear el elemento PNT para la gestión de la certificación pero sin asociarle la documentación para estar disponible desde nuestra aplicación por politicas de confidencialidad/seguridad de la compañía.
