### ISSUE TITLE
Paso 4: no se puede acceder porque el icono sigue saliendo como AVATAR

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#319]

**Comment by FranGomezVenegas** [comment]
Ese icono 'Avatar' se llama "procedure-sops", Este elemento pertenece al elemento de las pestañas (aunque esté por debajo de éstas). El tema por el cual no aparece el icono de PNT es porque estaba pensado para las pestañas que pertenecen a los procesos porque es en éstas a las que se les asocia los PNT, como las pestañas sobre PNTs no son de proceso pues al elemento no le llega la información que necesita para 'pintarse' y da fallo. 
Este elemento era una prueba de concepto. Lo he deshabilitado. Ya no va a aparecer ni para los PNTs el 'Avatar' ni el icono de PNT para las pestañas de proceso como aparecía antes. Vamos a añadir un icono al lado de cada opción del menú de procesos que tenga PNTs asociados con el color azul/rojo si están certificados o hay pendientes.

**Comment by cyberflor** [comment]
¡queda una pantalla más limplia!
