### ISSUE TITLE
Paso 8 y 9: se completa el certificado y cambia el estatus correctamente, pero no se puede leer la notificación en el panel de notificaciones, ni se ve el pop-up azul de que la acció se realizó correctamente

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#321]

**Comment by FranGomezVenegas** [comment]
Antiguamente la respuesta de la API devolvía un par de atributos llamados error_value_en/es. Esto se mejoró por el enviar del par message_en/es + el boleano is_error, para indicar si es un mensaje de error o de no error. Parece que en el FrontEnd de SOPs no se aplicó el cambio para estar alineados, corregido y funciona.

**Comment by cyberflor** [comment]
no he podido comprovarlo pq tengo todo los 3 PNT's certificados, pero cierro incidencia. y hago nota para hacerlo en la 2º ejecución general
