### ISSUE TITLE
Paso 5: formato de diálogo incorrecto, debería ser tipo DIAL.001, que solamente aparezca un espacio par escribir un número no text, es confuso tal y como está configurado ahora. Haría lo mismo con el resto de botenes: Zanjarla y confirmar. Admás confirmarla no es lo mimo que Entrar? habría que quitar uno de los votones, yo quitaria el de entrar

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#325]

**Comment by FranGomezVenegas** [comment]
Vamos por partes ....
1º, si se ha cambiado el diálogo para 'Reabrir' para que se indique la id de la incidencia a reabrir ... PERO .... también sigue el elemento para añadir texto ¿Por qué? Porque para reabrir una incidencia se debe justificar el motivo y esto es obligatorio, para que la persona que reciba la incidencia sepa 'por qué demonios' se ha reabierto una incidencia que ya estaba cerrada.
En confirmación y en Cerrar también la nota es a modo de justificación. La confirmación requiere de dejar una evidencia de que se confirmó y esto será la nota ... que a futuro haremos lo posible para permitir que las notas lleguen mendiante envío de correo electrónico también. 
Al cerrar una incidencia se debe dejar constancia del motivo ... de hecho a futuro el formulario se mejorará para permitir clasificar el tipo de solución etc ... pero por ahora es solo una nota.

Esto no me lo he inventado yo, es lo que está establecido en los sistemas de gestión de incidencias, como Remedy o JIRA (que es el que se está estableciendo como standard en la industria). Yo tengo experiencia en trabajar con estos sistemas y además soy certificado por ITIL y, repito, es el modus operandi de la industria.

**Comment by cyberflor** [comment]
perdón por escribir botones con V. 

Entiendo lo que me dices e integro la información
