### ISSUE TITLE
BE - Permite añadir muestra a una tanda que está iniciada

### ISSUE THREAD

**Issue by FranGomezVenegas** [FranGomezVenegas/LP#329]
Una vez se inicia una tanda no se puede cambiar el contenido de esta..

Acabo de volver a probar y a mi me funciona correctamente. Haz un video donde pueda ver cómo consigues que suceda

**Comment by cyberflor** [comment]
verficada, he creado una tanda nueva y le he añadido una muestra. Da error "undefined.undefined.EM_BATCH_INCUB_ADD_SMP : The batch tostada already started therefore alter its content is not allowed." no deja añadir muestra a tanda aún estando sin iniciar y vacía.

*****ESTA INCIDENCIA NO ESTÁ EN EL EXCEL

**Comment by cyberflor** [comment]
pendiente de volver a verificar cuando vuelva a funcionar correctamente la incubación.

*****ESTA INCIDENCIA NO ESTÁ EN EL EXCEL
