### ISSUE TITLE
Paso 58: 1ºhacer clic sobre icono cerrar sesión  2º volver a acceder con los datos que se han guardado en el formulario, al  haber estado con la sesión abierta anteriormente debería acceder sin problema. Pero no se puede acceder, se bloquea cargando como si fuera a iniciar. Que sea un protocolo de seguridad que no se guarde el usuario y la contraseña por defecto, por lo tanto deberían desaparecer la información del usuario del formulario al cerrar la sesión con el icono "salir" 

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#334]

**Comment by cyberflor** [comment]
cuando se sale haciendo clic en el icono de cerrar sesión no se puede volver a iniciar sesión aún escribiendo la contraseña correcta.

**Comment by cyberflor** [comment]
Cuando se sale haciendo clic en el icino cerrar sesión 

1º la página de inicio no se ve correctamente tanto en:

- es6prodNew 
![image](https://user-images.githubusercontent.com/60526983/85417974-89bc3900-b570-11ea-98d2-3a59d3410462.png) 

 - uncompNew
![image](https://user-images.githubusercontent.com/60526983/85418084-a8223480-b570-11ea-80b9-39e43cf1d663.png)

se puede ingresar datos pero no carga bien la páginia principal ni el resto de pantallas

- es6prodNew 

![image](https://user-images.githubusercontent.com/60526983/85417865-685b4d00-b570-11ea-992d-72d3616398af.png)

 - uncompNew

![image](https://user-images.githubusercontent.com/60526983/85418324-f0d9ed80-b570-11ea-85be-2a33d5bfec83.png)

**Comment by FranGomezVenegas** [comment]
Ya resuelto, al salir debe borrar todas las variables del contexto EXCEPTO el idioma ... al no borrar el idioma ya funciona correctamente
