### ISSUE TITLE
Paso 5: NO PUEDO  pasar la muestra 259 de la tabla"2ªincubación

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#339]
Lo he visto, la he quitado de la tanda en la que la tenías y la he añadido a la tanda 'tandada', entonces si me ha permitido iniciar y terminar la tanda  y entonces la muestra ha pasado a lectura de placa. Creo que el problema viene porque el nombre de la tanda contenga un símbolo "." ... por fa, crea una tanda sin punto y mira a ver si te funciona.... 
Si, lo miraré de resolver, pero es importante que puedas seguir operando, míralo como una solución provisional!

Creo que es un problema con la INC2, más que el nombre de la tanda. Lo digo porque he creado una tanda de nombre QWERT  y ha funcionado, otra llamada P.P y tb, las dos con INC_1. En cuanto he creado una llamada 1234 y le he asignado INC2 me ha fallado ...

**Comment by cyberflor** [comment]
la pongo en verificado - no finciona

**Comment by cyberflor** [comment]
ha pasado lo siguiente:
- No admite nombre con símbolo excepto el guión que sí lo acepta = p-r-o-v-a-d-a
- No admite mix de mayúsculas y minúsculas = PROvada
- Sí admite una letra capital, y eso permite repetir nombre = Provada +pROVADA
- Sigue fallando la INC2

![image](https://user-images.githubusercontent.com/60526983/81406521-09658400-913a-11ea-96e3-6a9f8747c744.png)

**Comment by cyberflor** [comment]
En esta última verificación no se puede asignar muestras a ninguna tanda @FranGomezVenegas

**Comment by FranGomezVenegas** [comment]
a ver ... la incidencia habla de una muestra, la 257 y que no deja pasar de la 2ª incubación. Pero la muestra está termitnada ... ahora bien ... '2 days ago' hay nuevos comentarios y estan habalndo de otras incidencias ¿en qué quedamos? ¿Cuál es el problema actual? porque creo que aqui hay mezclados el paso 5 con el 23 y con el 31 .... ¿me lo aclaras?

**Comment by FranGomezVenegas** [comment]
Supongo que era el problema de la botonera de 2ª incubación, ya funciona, pruebalo de nuevo

**Comment by FranGomezVenegas** [comment]
El problema ORIGINAL de esta incidencia NUNCA fue el nombre de la tanda, el problema era que la tanda se asignó a la incubadora INC2 que no tenía (y sigue sin tener) lecturas de temperatura. El problema es que no se iniciaba pero no daba un mensaje del motivo, ahora sí lo da, es este:  La libreta de la incubadora carmen2 no tiene lecturas anotadas todavía. Donde carmen2 es el nombre de la tanda ...

**Comment by cyberflor** [comment]
solamente falta que funcione ingresar lectura de temperadura y esto estará acabado.
