### ISSUE TITLE
MEJORA->registrar IPs, saber en qué dispositvo se abrió la aplicación

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#341]

**Comment by FranGomezVenegas** [comment]
Añadido al sistema! Al autenticar se toma la ip de la petición (es decir quien ejecutó el endpoint authenticate) y se añade a los datos de sesión de usuario.
Lo próximo sería crear un proceso, que añadiré a APP-Enhancements, mediante el cual un cliente, ya sea por temas de suscripción o por temas de seguridad del propio cliente, dé de alta las IPs desde donde se pueda conectar al sistema y no se pueda acceder si no es desde una de estas IPs declaradas como disponibles/habillitadas.
