### ISSUE TITLE
Paso 12: se recibe pop-up azul como confirmación, y debería ser mensaje de error "Dato introducido no válido" (al ser un valor negativo) de la entrada del valor y la muestra desaparece de la tabla para ir a la tabla de identificación de micoorg. automáticamente (LISTA COMENTARIO)

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#343]
Añadidos parámetros para definir valor mínimo y/o valor máximo permitido a nivel de configuración de los límites de tal manera que, por ejemplo, ahora no permite valores negativos porque hemos indicado como valor mínimo permitido el valor 0, inclusive. 
De esta manera permitimos qu se configure para cualquier caso y no solo para este módulo en particular

**Comment by cyberflor** [comment]
Pasa el mismo error en la tabla de la etapa Lectura de placas del proceso, muestra utilizada 258 y se ha introducido el valor -8.

**Comment by cyberflor** [comment]
No tengo muestras en la pestaña lectura de placas, así qye he pasado la muestra 438 a incubación. pero no se puede seguir avanzando para verificar este punto porque se bloquea en la tabla 2a incubación esto está relacionado con la incidencia #339 se volverá a verificar cuando se solucione la incidencia bloqueante.

**Comment by FranGomezVenegas** [comment]
Vale, encontré el problema por el cual la botonera de la 2ª incubación no funcionaba. Ya funciona y se pueden añadir muestras a tandas ....
