### ISSUE TITLE
Paso 13: se escribe comnetario en la muestra 877 , se acepta y se actualiza la tabla manualmente pero no aparece comentario en la muestra y a abrir de nuevo para escribir comentario para  muestra 878 aparece lleno el dálogo con el comentario de la muestra anterior. (MIRAR COMENTARIO)

### ISSUE THREAD

**Issue by cyberflor** [FranGomezVenegas/LP#344]

**Comment by cyberflor** [comment]
pasa el mismo error en la etapa muestreo de muestras

**Comment by FranGomezVenegas** [comment]
A mi no me sucede ... en ambos muestreos, si entro una nota le aparece a la muestra sin necesidad de refrescar manualmente y cuando voy a poner nota a otra muestra la pantalla del comentario tiene el campo vacío y listo para entrar una observación

**Comment by cyberflor** [comment]
En la tabla muestro de muestras se puede añadir comentario ala muestra 429, pero al querer añadir comentario a otra muestra 447 aparece el comentario anterior en el diálogo y al escribir el comentarior nuevo la mueve de posición.

**Comment by FranGomezVenegas** [comment]
Resuelto, deshabilité el reseteo porque funcionaba al pulsar Enter pero daba problema al pulsar el botón, he corregido este problema y habilitado el reseteo, funciona! :)

**Comment by cyberflor** [comment]
comentario en las tablas de muetreo , tanto de personal como de muestras, al añadir comentario reposiciona la muestra (que se puede buscar con el buscador de la tabla rápidamente). Pero lo importante es que se puede añadir comentario de forma limpia.
