### ISSUE TITLE
Resultado Fuera Límite y Acción Correctiva aún no cerrada.

### ISSUE THREAD

**Issue by FranGomezVenegas** [FranGomezVenegas/LP#356]
Se ha añadido la funcionalidad para que mientras la accion correctiva esté abierta entonces la celda para entrar el resultado de esa muestra queda bloqueada. Además se añade en el detalle el motivo del bloqueo, que no es otro que el de que la accion correctiva aun esta pendiente de cierre

**Comment by cyberflor** [comment]
genial! fucniona--> pop-up rojo avisa "La muestra 262 tiene registros de auditoría sin firmar"
provado en la pantalla de Personal id.micoorg. & id.microorg
