### ISSUE TITLE
FE: E-Sign y Confirmación de usuario - Razones o motivos

### ISSUE THREAD

**Issue by FranGomezVenegas** [FranGomezVenegas/LP#387]
Cuando se active, no sólo debe activar sino que se debe tipificar una de las siguientes tipologías para la razón o motivo:
- Visible / No Visible
- Opcional / Obligatorio 
- Campo de texto libre
- Campo de tipo lista
- Campo de tipo lista + permitir texto libre

Por el momento sólo tenemos resuelto el de texto libre, es opcional.

**Comment by Joelsn** [comment]
No se puede cerrar el diálogo de reenter result ni con botón Cancelar ni con el botón Escape, El FE nos da un mensaje de que se realiza la acción pero no veo que se realice la Pregunta y Respuesta al BE para cerrar el diálogo
