### ISSUE TITLE
Automatiso para MD-STAGES, MD-SPECS, MD-PROGRAMS, etc...

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#429]

**Comment by FranGomezVenegas** [comment]
Este ticket ha fomentado la creación de una utilidad (MD Parsers) que requiere ser abordado en un proyecto donde cada MD Parser va a tener que ser generado como un tema (no incidencia) y en este proyecto se generará la documentación para explicar qué MD Parsers disponemos y qué hace cada uno de ellos.
