### ISSUE TITLE
en Excel: Automatismo para la pestaña "md_lists" que esconda o muestre la columna  TESTING_GROUP al poner el valor TRUE OR FALSE

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#430]

**Comment by FranGomezVenegas** [comment]
Se ha añadido un checkbox que tiene una macro que permite la acción automática:
Sub BusRule_TestingGroupUsage()
    Dim selectedValue As Boolean
  
    Worksheets(ActiveSheet.Name).Activate
    selectedValue = Range("BUSRULE_USE_TESTING_GROUP").Value
    Cells.EntireColumn.Hidden = False
    If (selectedValue) Then
        Columns("M").EntireColumn.Hidden = False
    Else
        Columns("M").EntireColumn.Hidden = True
    End If
End Sub

![image](https://user-images.githubusercontent.com/26067165/113523613-e9884b80-95a8-11eb-9fd5-5de267115f9c.png)
