### ISSUE TITLE
En "DbObject.createPlatformSchemaAndBasetable" ejecutar todas las sentencias automaticamente y no tener que ir comentando la anterior -> Hasta que no se crea el esquema Config y su tabla Zzz_db_error_log, el proceso se tiene que ejecutar objeto a objeto

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#435]

**Comment by FranGomezVenegas** [comment]
Esto habrá que mejorarlo en un futuro, en vez de pasar null se debe pasar el nombre de la plataforma ... a futuro ...
![image](https://user-images.githubusercontent.com/26067165/113783137-97bffc80-9733-11eb-9f96-b35aecc888ec.png)
