### ISSUE TITLE
Para la tabla de unidades de medida, no solo crear la tabla sino también añadir el contenido de todas las unidades de medida para la nueva bd

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#439]

**Comment by FranGomezVenegas** [comment]
'tablas de medida'? unidades de medida o de qué se trata? añade un comentario para situar en contexto el ticket o no queda claro de qué se trata ...

**Comment by Joelsn** [comment]
en el backend, dentro de trazit -> config -> tables, encontraremos units_of_measurement. Esta tabla la hemos creado en em_air_all a partir de em_demo_a, pero se crea vacía y hay que mirar una forma de optimizar la creación, ya que sino, hay que pasar las unidades de forma manual y en pequeñas porciones.

**Comment by FranGomezVenegas** [comment]
Se ha creado una solución más genérica, no solo específica para esta tabla, evidentemente que resuelve esta necesidad. Consiste en:
Clase FromInstanceToInstance, método tableContent().
Recibe 4 argumentos: schemaName, tableName, sourceDB, destinationDB.

Eso si, dentro de las diferentes casuísticas o posibles escenarios, nos hemos centrado en resolver un único caso de uso (#1) de los diferentes posibles que se enumerarán a continuación.

El objetivo del método es, a día de hoy, es el de copiar el contenido de una tabla que está ubicada en el mismo lugar en ambas bds de una bd origen a una bd destino. En caso de que en origen no haya datos devolverla FALSE. En caso de tener algún problema también devolverá FALSE e indicaría el número de registros que sí se pudieron transferir y el total de registros que se deberían haber transferido de haber ido todo bien. Devolverá TRUE si tods los registros se copiaron con éxito.

Casos de uso:
#1. La tabla destino está vacía, el objetivo es mover CLONAR todo de origen en destino teniendo en cuenta que la tabla existe en ambos repositorios y en destino la tabla al menos contiene todos los campos que tiene la tabla en orígen y en destino no hay ningún otro campo que sea obligatorio y no exista en orígen.

#2. Que la tabla origen y la tabla destino no se llamen igual o no estén ubicadas en el mismo lugar de ambos repositorios.
#3. Permitir aplicar un filtro para no pasar TODO el contenido sino parte del contenido.
etc ...
