### ISSUE TITLE
Revisar porque no se han asignado los sop a los usuarios-> deployProcSopToUsers

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#444]

**Comment by FranGomezVenegas** [comment]
Se detectó el motivo. <>-data.user_sop.mandatory_level está definido mandatory y como no recibia valor no se podia crear. en labplanet no está como obligatorio, se ha pasado a opcional y cambiado la definición para que el creador de instancias de plataforma lo cree como opcional.

**Comment by FranGomezVenegas** [comment]
en em-air-allv2 y v3 ya ha funcionado correctamente con lo cual se cierra el ticket.
