### ISSUE TITLE
En el excel, user requeriments -> permitir que en la columna Roles se puedan añadir varios roles/valores*

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#445]
Como se tiene que pasar a procedure user requirements, tiene que pasar el valor que hay en el excel, cuando se hace un deploy procedure events debe mirar este valor, y si hay varios roles tiene que saber crear una linea en procedure events para cada roll.

**Comment by FranGomezVenegas** [comment]
Por defecto, la celda es de tipo lista pero se puede editar y podemos añadir varios roles separados por el símbolo |, Ejemplo: sampler|super_user, y el sistema lo interpretará como que la acción debe ser asignado a los roles de la lista. Si indicamos ALL entonces da acceso a todos los roles del proceso.
