### ISSUE TITLE
resolver la incidencia "all"

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#446]

**Comment by Joelsn** [comment]
En procedure events, no hay ningún roll que se llame "all", resolver el perfil de usuario "roll" -> hay dos cosas relacionadas

**Comment by FranGomezVenegas** [comment]
Importante tener en cuenta de que se trata de la palabra ALL (mayúsculas), all no se tiene en cuenta ni TODO ni todo etc ... solo ALL.
Al terminar de crear los procedure_events, el sistema mira si alguno tenía asignado el rol ALL y de ser así va a consultar por los roles del proceso y va a reemplazar este ALL por el del primer rol y va a clonar el registro para cada uno de los roles restantes.

En el ejemplo siguiente, tener en cuenta que hay un rol llamado all. La primer figura muestra el resultado 'intermedio' de cómo sería la primera creacion de contenido en este repositorio, la segunda una vez realizada la transformación ALLxRoles. Este ejemplo es meramente ilustrativo porque el sistema realizará las dos acciones conjutamente con lo cual la primera figura no se podrá capturar. Veríamos el resultado final, la segunda, directamente.

![image](https://user-images.githubusercontent.com/26067165/115142438-0a897b80-a042-11eb-8506-cdd76a0da9dc.png)


![image](https://user-images.githubusercontent.com/26067165/115142401-e4fc7200-a041-11eb-809e-79d9a4fe32cd.png)
