### ISSUE TITLE
Falta tabla de areas analizables de personal

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#447]
Se resuelve con subirlo a procedure_master_data, como el resto de datos maestros que se crean en  el Workbook de Excel

**Comment by FranGomezVenegas** [comment]
¿Tabla de instrumentos de personal? por fa añade más detalles para poner en contexto la incidencia o al menos el minuto y el nombre del video donde aparece

**Comment by Joelsn** [comment]
A la hora de subir los datos maestros al backend, en el excel -> MD_LIST tenemos en la columna J los accesorios del personal. La incidencia es que a la hora de subirlo al backend -> Tables, no hay nada creado para poder subir este tipo de objetos
