### ISSUE TITLE
 Cuando estamos en una sesión de testeo, hay que mirar porque no hace las comprobaciones y permite crear EM_BATCH_INCUB_CREATE, EM_BATCH_ASSIGN_INCUB, EM_BATCH_INCUB_ADD_SMP si no estan declaradas en procedureAtions

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#450]

**Comment by FranGomezVenegas** [comment]
Por ahora 'es asi', en testeo no se contempla el hacer este check

**Comment by FranGomezVenegas** [comment]
Se ha añadido la lógica como se ve en la figura 1, va a comprobar que las acciones relacionadas con los Steps activos del test (que serán las que se ejecuten) estén todas activadas para el proceso al que se va a ejecutar el test. De no ser así mostrará un mensaje, figura 2, indicando en qué steps y qué acciones existe un problema y se aborta la ejecución del test.

![image](https://user-images.githubusercontent.com/26067165/132982407-06af2354-de74-4d76-9760-4a59e2ea44ef.png)

![image](https://user-images.githubusercontent.com/26067165/132982482-cba7dbf2-8922-46e6-a25e-bbff0295ccd2.png)
