### ISSUE TITLE
En el proceso de creación registros, al subir la tabla "requirements" procedure_module_tables, el active debe de estar en True, si no nos dejara deployar

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#452]

**Comment by FranGomezVenegas** [comment]
Añadida la columna I:
="Script: insert into "&CARACTER(34)&"requirements"&CARACTER(34)&".procedure_module_tables ("&C1&", "&D1&", "&E1&", "&F1&", "&G1&", "&H1&", "&I1&") values ("

=SI(I2="true";REEMPLAZAR(ScriptBaseModuleDbTables;1;8;"")&C2&", "&D2&", "&E2&", '"&F2&"', '"&G2&"', '"&H2&"'"&","&I2&");";"")
