### ISSUE TITLE
Al intentar introducir un comentario de muestreo en muestreo de muestras, los registros no aparecen tras actualizar la pestaña

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#480]
![image](https://user-images.githubusercontent.com/81186702/119677902-63b5ad80-be3f-11eb-8c6b-7b9a55abafd9.png)

**Comment by FranGomezVenegas** [comment]
Creo que sucedió en un momento donde la bd se fritó porque ahora que está bien funciona, pruebalo de nuevo.
