### ISSUE TITLE
A la hora de crear una tanda de incubación, se le pone nombre y se le da a crear, pero no llega a mostrar la tanda cread. Si se crea porque al poner otra tanda con el mismo nombre pone que ya existe

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#483]
![image](https://user-images.githubusercontent.com/81186702/119909094-59390800-bf54-11eb-93ce-31978c864a20.png)

**Comment by FranGomezVenegas** [comment]
Cuando pase algo así, por fa, incluye el nombre que le diste a la tanda para tener más detalle del tema ...
