### ISSUE TITLE
A la hora de crear un lote de produccion nuevo, le damos nombre y nos sale el siguiente mensaje : One incubator batch called Lote 2 already exist in procedure em-demo-a, tanto en ingles como en español. solucion: hacer mensaje en español que diga: Un lote de incubadora ya utiliza el nombre "Lote 2", en el proceso em-demo-a

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#485]

**Comment by FranGomezVenegas** [comment]
Vaya!!! El mensaje estaba apuntando al mensake de incubBatchExist, Se ha creado el mensaje productionLotAlreadyExists y se apunta a este, es el correcto.

**Comment by Joelsn** [comment]
He repetido el caso y no he visto que haya cambiado, el caso es cuando creas un lote de produccion y lo nombras con un nombre existente, sale ese mensaje, sale solo en inglés
