### ISSUE TITLE
Al darle a ¡Reabrirla!, aparece un diálogo con cuadro de texto con boton en el cual puedes poner el numero de incidencia, cuando le das a aceptar sale mensaje azul en blanco y no pasa nada. Solución: Deberia poder reabrir una Incidencia previamente cerrada, no abrir un dialogo de texto.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#495]

**Comment by FranGomezVenegas** [comment]
El diálogo es para que entres el id de la incidencia a reabrir porque la tabla es de incidencias activas con lo cual reabrir no usa el registro de la tabla sino que necesita que indiques el id de la incidencia a reabrir, el texto es el motivo de reabrirla
