### ISSUE TITLE
Posible Mejora -> El lenguaje de la pantalla de los SOP's esta mezclado en inglés y español, al intentar ponerlo en castellano o inglés no cambia.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#498]

**Comment by FranGomezVenegas** [comment]
No podemos traducir los valores, sólo las etiquetas que son de sistema. Es decir, el nombre del atributo si es traducible pero el valor no, si hay algún nombre de atributo no traducido dimelo, es importante que pongamos ejemplos y seamos concretos ...

**Comment by Joelsn** [comment]
Perdona que he sido muy poco concreto, en la pantalla de SOP's, en los dos ejemplos que tenemos pone: procedure, SOP Name, summary y my certification status, están en inglés.
pero la descripción del SOP en concreto si esta en español. Esos no se pueden cambiar?
