### ISSUE TITLE
En la pestaña de muestras pendientes de lecturas de placas, Habría que mirar de cambiar este mensaje que nos da al intentar pasar una muestra sin haber hecho la auditoria previamente. DataSample_SpecialFunctionReturnedFALSE (*** This errorCode has no entry defined in messages property file) [1348, em-demo-a]

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#501]

**Comment by FranGomezVenegas** [comment]
Resuelto, PERO!!! por motivos de arquitectura el mensaje no es traducible en este caso, así que por el momento lo aceptamos si aparece al menos el mensaje aunque no se traduzca pero antes de cerrar el ticket asignarle la label Quarantine, para saber que queda esa parte pendiente ...
