### ISSUE TITLE
Para realizar una selección de incubadoras, no aparece las incubadoras disponibles a no ser que le des al botón de actualizar en la barra de tandas. Solución: Debería actualizarse la pantalla automáticamente a la hora de abrirla.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#506]

**Comment by FranGomezVenegas** [comment]
Seguramente te ha pasado cuando se ha colgado la bd. Si, la lista de incubadoras debe cargarse al abrir la ventana ... pero si hubo problema de bd y no se cargó ... pues eso.

**Comment by Joelsn** [comment]
dejo abierta porque sigo probando y le cuesta como en el caso de programs, cierro de todos modos?

**Comment by FranGomezVenegas** [comment]
Revisado y corregido, se ha asignado la acción de buscar las incubadoras al botón
