### ISSUE TITLE
Habría que cambiar el mensaje que nos da a la hora de crear una tanda: EM_BATCH_INCUB_CREATE. Error: No encontrado valor para el parámetro batchName que es declarado como obligatorio para la acción EM_BATCH_INCUB_CREATE Solucion: Para crear una tanda hace falta poner un nombre

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#509]

**Comment by FranGomezVenegas** [comment]
El tema es que el mensaje, al menos de momento y por arquitectura, no puede ser tan personal. Se controla si algún parámetro obligatorio no se ha indicado ... pero esto lo hace para cualquier acción, no es personal para este caso particular, por eso que por el momento no es posible personalizarlo a este nivel. Se asigna Quarantine por si en el futuro se retoma, pero no se considera un fallo  , de momento, aunque se entiende el objetivo.
