### ISSUE TITLE
En la etapa de incubación, cuando tenemos una muestra a la espera de realizar la primera incubación y le damos a quitar muestra en la segunda incubación, nos permite sacar esa muestra de la primera incubación. Solución: Debería salir un mensaje que dijese que esa muestra no se encuentra en la segunda incubación

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#512]
![inctest2](https://user-images.githubusercontent.com/81186702/121544341-ee82d480-ca09-11eb-97e1-e70fae8e802c.png)
![inctest1](https://user-images.githubusercontent.com/81186702/121544349-efb40180-ca09-11eb-96b5-e5e39a0e4357.png)

**Comment by FranGomezVenegas** [comment]
Corregido en FE
