### ISSUE TITLE
En el dialogo de la lista de incubadoras, hay que darle a actualizar para que aparezcan, debería aparecer autormáticamente sin necesidad de actualizar.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#519]

**Comment by FranGomezVenegas** [comment]
Está hecho para que así sea, se carga al abrir la pantalla pero a veces no carga bien y por eso hay que dar a actualizar para que lo vuelva a intentar. Creo que ha coincidido con un problema de bd, la cierro y la pongo en quarantine por si sucede muy a menudo ... pero diría que es un problema derivado con los cuelgues de bd más que de problema en la pantalla en sí.
