### ISSUE TITLE
Cuando se desmarca una muestra previamente seleccionada, y se hace click en una accion(botón siguiente por ejemplo) sigue teniendo respuesta sobre la última muestra seleccionada seleccionada a pesar de no estar seleccionada, esto no debería ser así y se tendria que poder desactivar.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#520]

**Comment by Joelsn** [comment]
Este caso ocurre también en la pestaña de "Muestras pendientes de Lectura"

**Comment by FranGomezVenegas** [comment]
La 486 es la misma incidencia, el componente tabla trabaja de la misma manera entonces si la deseleccion no funciona en una pantallla tampoco funciona en otra porque es un problema general del componente tabla.
