### ISSUE TITLE
Nos deja firmar toda las auditorias cambiando de sesión en Wiam, pero cuando se firman no avanza a la siguiente etapa

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#524]

**Comment by FranGomezVenegas** [comment]
Hay que avanzar a mano, si? Pero funciona? No está conectado para el paso automático ... si funciona a mano ... es suficiente ... lo pongo en quarantine por si lo volvemos a retomar pero no creo ... de momento no :)

**Comment by Joelsn** [comment]
A mano tampoco funciona!! por eso te comentaba que el problema con el botón "siguiente" debe de estar relacionado. Normalmente nos da el mensaje "Null" ahora directamente no ha puesto nada en el mensaje, última revisión 2021/06/14 15:27

![auditoria](https://user-images.githubusercontent.com/81186702/121899546-d0c4b080-cd24-11eb-8ba1-9b88d1ca5445.png)
![auditoria2](https://user-images.githubusercontent.com/81186702/121899564-d4583780-cd24-11eb-9d10-3b17e643c8d7.png)

**Comment by FranGomezVenegas** [comment]
Ya debe funcionar, prueba de nuevo porfa
