### ISSUE TITLE
En la etapa de microorganismos, cuando intentamos pasar una muestra a la siguiente etapa presionando botón siguiente, nos da un mensaje: "null" y la muestra no avanza.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#525]

**Comment by FranGomezVenegas** [comment]
No sé por qué pero le puse que no pasara y sin mensaje de motivo, por eso salía mensaje en blanco, le he dicho que pase y ya está ...

**Comment by Joelsn** [comment]
![microorganism](https://user-images.githubusercontent.com/81186702/122040822-94528c80-cdd8-11eb-9883-c0ee3b4c53d3.png)

he podido tirar la muestra para atrás pero pasa lo mismo al intentar volver a traerla a la misma etapa
