### ISSUE TITLE
No nos permite envíar la muestra al paso anterior, nos da este mensaje: Excepción de devolución.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#526]

**Comment by Joelsn** [comment]
![muestreo de muestreo retroceder negado](https://user-images.githubusercontent.com/81186702/121921600-6e29df80-cd39-11eb-87e5-0c18c8853fea.png)

**Comment by FranGomezVenegas** [comment]
A ver, esta es la primera etapa, básicamente lo que debemos hacer es quitar el botón porque no se puede enviar a la anterior etapa si está en la primera etapa ¿verdad?
