### ISSUE TITLE
Al cancelar el diálogo de añadir a una investigación sin ninguna muestra seleccionada previamente, sale el siguiente mensaje: Object sample_analysis_result*100 already added in 72

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#528]
![desv](https://user-images.githubusercontent.com/81186702/121933826-daf7a680-cd46-11eb-9a62-7d9fdf240250.png)
![desv2](https://user-images.githubusercontent.com/81186702/121933828-dc28d380-cd46-11eb-8f4f-af588c24534d.png)

**Comment by FranGomezVenegas** [comment]
Aquí no debería ni intentar hacer la acción porque si cancelamos el diálogo es como 'abortar misión', corregido el FE para que aborte misión al pulsar el botón cancelar.
