### ISSUE TITLE
Al darle al botón cancelar al diálogo de "añadir a una investigación" con una investigación seleccionada, da este mensaje: The record select id, invest_id from "em-demo-a-procedure"."program_corrective_action" where result_id=? and status NOT IN (?) does not exist in table [100, CLOSED] in procedure "em-demo-a-procedure".

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#529]
este mensaje me ha salido sólo una vez y no he podido hacer screenshot, seguiré probando para añadir el porqué sale

**Comment by FranGomezVenegas** [comment]
Diría que si damos a cancelar debe 'abortar misión' y ya lo hace, con lo cual esta acción en este caso concreto no se ejecutará.

**Comment by Joelsn** [comment]
la  voy a cerrar porque por lo que veo funciona mucho mejor, si vuelve aparecer reabro!
