### ISSUE TITLE
AGUA - Al asignar una observación durante el muestreo, Aparece diálogo para introducir la observación pero no aparece la observación, aparece este comentario: Comentario añadido a muestra 51 correctamente. Debe de ser porque no se aprecia la columna de observaciones

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#535]
![fq ensayos](https://user-images.githubusercontent.com/81186702/122221725-dac7ea00-ceb1-11eb-8e60-2914aecda5d0.png)

**Comment by FranGomezVenegas** [comment]
si aparece, lo que pasa es que (y no sé por qué) cambia la posición de las muestras y entonces la 51 ya no está donde estaba y por eso no ves el comentario ... pero si lo añade. ...
