### ISSUE TITLE
AGUA - No es posible cambiar un valor previamente introducido como outofspecMax por In, pero In a outofspecMax si se puede.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#537]
![rango valores falla](https://user-images.githubusercontent.com/81186702/122276076-b5080880-cee4-11eb-9b91-946093624917.png)

**Comment by FranGomezVenegas** [comment]
No entiendo, yo entro 0.1 y me funciona .... dice In

![image](https://user-images.githubusercontent.com/26067165/122307092-f363ee80-cf09-11eb-99f6-fab39624fd79.png)

**Comment by Joelsn** [comment]
Haciendo pruebas he  visto que no es un problema del valor, sino que si había un valor previo por ejemplo "70" y daba outofSpecMax , no es posible cambiarlo por 0.1 para que de "In", nos da este mensaje: The current result status is REVIEWED and it does not allow enter results for 176 in procedure "proc-deploy-config".
