### ISSUE TITLE
AGUA - CALENDARIO - Los días no están bien escritos de forma progresiva de lunes hasta domingo, habría que ordenarlos y quedará perfecto!

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#555]
![calendario](https://user-images.githubusercontent.com/81186702/123094663-7070f580-d42d-11eb-8a75-8bedf7605a4b.png)

**Comment by FranGomezVenegas** [comment]
No consigo reproducirlo, dime cómo ! :)

**Comment by FranGomezVenegas** [comment]
Estresalo a ver si consigues reproducir el problema y me dejas saber cómo

**Comment by Joelsn** [comment]
![image](https://user-images.githubusercontent.com/81186702/125317072-01563500-e339-11eb-9f11-11af702132bf.png)
![image](https://user-images.githubusercontent.com/81186702/125316910-dbc92b80-e338-11eb-8920-41ed7a14610c.png)

**Comment by Joelsn** [comment]
De primeras funciona bien, si se empieza a navegar por los meses es cuando se descuadran los días
