### ISSUE TITLE
En el calendario, al clicar sobre el mes o el año, aparece el diálogo pero  no se ven los meses y los años a no ser que pases el ratón por encima, daría un punto que se mostrasen 

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#556]
![calendario2](https://user-images.githubusercontent.com/81186702/123095005-dbbac780-d42d-11eb-90f1-0cb097a74bb7.png)

**Comment by FranGomezVenegas** [comment]
![image](https://user-images.githubusercontent.com/26067165/124044360-8d00c500-da0d-11eb-9881-e58d9540c615.png)

**Comment by Joelsn** [comment]
no la he validado porque no lo veo en azul, esta configuración de html no va por el SRC verdad?
