### ISSUE TITLE
AGUA - Al entrar resultados OUT no genera desviaciones

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#558]

**Comment by FranGomezVenegas** [comment]
A ver ... 110 es la muestra y 516 y 517 son los ensayos ... se revisan los ensayos ... mira bien la estructura de datos ...

**Comment by Joelsn** [comment]
![FQ ENSAYOS 110](https://user-images.githubusercontent.com/81186702/123413243-d63aba00-d5b2-11eb-9a37-cf59f13d9c1e.png)
![FQ Ensayos pendientes](https://user-images.githubusercontent.com/81186702/123413245-d63aba00-d5b2-11eb-8b17-81bf2e5dab35.png)

**Comment by FranGomezVenegas** [comment]
Corregido, faltabas las tablas en la bdd para este proceso!
