### ISSUE TITLE
AIRE - CapaRequired debería ser false o true, pero no puede estar vacío 

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#561]
![DESVIATION](https://user-images.githubusercontent.com/81186702/123635626-2c5e6600-d81c-11eb-9237-bc82a6773dd6.png)

**Comment by FranGomezVenegas** [comment]
En el último src que te he pasado debería estar solucionado! prueba y me dejas saber ...

**Comment by Joelsn** [comment]
Sigo sin poder aplicar Decision sin CAPA, me da el siguiente mensaje: Error building the call to the API for the action INVESTIGATION_TAKEN_DECISION. Error: Not found value for the param capaRequired which is mandatory for the action INVESTIGATION_TAKEN_DECISION

**Comment by FranGomezVenegas** [comment]
ok, lo miro ...
