### ISSUE TITLE
AGUA - En diálogos, cuando tenemos una muestra seleccionada y abrimos el diálogo de añadir investigación, no aparecen las investigaciones creadas

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#563]

**Comment by FranGomezVenegas** [comment]
Faltó esta linea en stateChanged de proc-deploy-webcomponent-env-monit
![image](https://user-images.githubusercontent.com/26067165/123946543-9eab8380-d99f-11eb-937f-21cc191c811e.png)

this.openInvestigationsListRows=state.procDeploy.openInvestigations;
