### ISSUE TITLE
FE - AIRE Desviaciones - No debería poder crearse investigación ni abrirse el diálogo de añadir investigación sin señalar una muestra previamente

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#564]

**Comment by FranGomezVenegas** [comment]
En Agua si lo hace bien?

**Comment by FranGomezVenegas** [comment]
Cierra esta si se debe al tema de haber seleccionado-deseleccionado lineas antes ... porque entonces esta incidencia es la otra que tenemos para este problema y no algo concreto sobre esta acción del sistema.
