### ISSUE TITLE
AIRE/AGUA - Fe - Registrar Muestra - Al registrar una Nueva muestra, el programa permite crear una muestra sin asignar Turno ni Lote. Debería ser obligatorio poner Lote y Turno

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#565]

**Comment by FranGomezVenegas** [comment]
Aplicado tanto a Aire como Agua:
Si hay varios campos te saldrá la lista de campos ... y es bilingüe :)

![image](https://user-images.githubusercontent.com/26067165/124048684-2d0f1c00-da17-11eb-8248-855814483d91.png)
