### ISSUE TITLE
Nos está saliendo un error de llamada tanto cuando pasamos el ratón y se abre el diálogo de creación de muestra en el mapa y cuando elegimos el turno, en ambos casos es en template-stamp.js linea 138

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#567]
![321](https://user-images.githubusercontent.com/81186702/124169430-896d4c80-daa6-11eb-926f-f6f90afa090b.png)
![2313](https://user-images.githubusercontent.com/81186702/124169436-8a05e300-daa6-11eb-948d-af661eaf2a5e.png)

**Comment by FranGomezVenegas** [comment]
Requiere este ajuste en la pantalla:
Añadir ambas cosas
![image](https://user-images.githubusercontent.com/26067165/125369347-549da700-e37c-11eb-881c-d4f22ed0aa0d.png)

**Comment by Joelsn** [comment]
He comprobado que estaba añadido este cambio, pero el mensaje me sigue apareciendo el mensaje de "listener method 'onlistchange' not defined".

**Comment by FranGomezVenegas** [comment]
Esto requiere el refactor del componente field-list .... se hará .. a futuro ...

![image](https://user-images.githubusercontent.com/26067165/125529104-52414385-dfb9-4eac-804c-76cf362074e2.png)

**Comment by Joelsn** [comment]
Se soluciona al pasar el ratón, pero vuelve a aparecer cuando elegimos turno y lote

![image](https://user-images.githubusercontent.com/81186702/125925919-61c1f2de-abc6-444a-bce9-ec7ff9b6f8d9.png)

**Comment by FranGomezVenegas** [comment]
Este lo necesita aquí
![image](https://user-images.githubusercontent.com/26067165/125931663-dd425e69-8928-45e8-b604-18a10c1e13e6.png)
