### ISSUE TITLE
Al darle al botón actualizar de la incubadora 1 y 2, aparece un error que nos dice que el botón actualizar no es una función, pero la acción de actualizar si que la realiza, el error parece estar en em-demo-a-sample-incub-batch.js:82

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#568]
![image](https://user-images.githubusercontent.com/81186702/124173798-d43d9300-daab-11eb-8c9a-ff12e0116553.png)

**Comment by FranGomezVenegas** [comment]
Esta incidencia es algo compleja ... pero creo que la he solucionado ... prueba con el nuevo src a ver ...

**Comment by Joelsn** [comment]
Sigue ocurriendo lo mismo..., de todos modos no es bloqueante por ahora

**Comment by FranGomezVenegas** [comment]
en em-demo-a-batches, la función se debe llamar refreshButtonClicked pero se llamaba refreshButton. Corregido.

**Comment by Joelsn** [comment]
perfecto!!!!!!
