### ISSUE TITLE
Al añadir una muestra a la tanda, nos sale el siguiente error Uncaught (in promise) TypeError: Cannot read property 'toastErrorMessageWithApiResponse' of undefined, la acción la hace y la deshace sin problemas, pero sale este mensaje, parece encontrarse en: 0module-endpoints-actions-env-monit.js:203 

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#569]
![image](https://user-images.githubusercontent.com/81186702/124175276-b7a25a80-daad-11eb-8f5d-1e555a0b0bdb.png)

**Comment by FranGomezVenegas** [comment]
No se puede reproducir. Creo que era un problema derivado de aquella otra incidencia relacionada con que el nombre de la función de refrescar batches no tenía el nombre correcto, al resolver aquel error se resuelve esta porque esta acción pretende refrescar la pantalla.... prueba de nuevo y me dejas saber.

**Comment by Joelsn** [comment]
cierto, no se ha podido reproducir, valido porque funciona perfect la incubación
