### ISSUE TITLE
FE- AIRE, Ha vuelto a salir el problema a la hora de asignar una Decisión sin el Trackwise, Error al crear la llamada a la API para la acción INVESTIGATION_TAKEN_DECISION. Error: No encontrado valor para el parámetro capaRequired que es declarado como obligatorio para la acción INVESTIGATION_TAKEN_DECISION

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#571]

**Comment by FranGomezVenegas** [comment]
Ahora si! Y era un problema 'de chiste, sin serlo'.

hay dos maneras de mirar si un atributo existe en una estructura, la que me gusta y suelo aplicar es comparando con 'undefined' pero no es necesario añadirlo, esa es la segunda opción. Lo que pasa con la segunda opción es que si el valor es un booleano y el valor es false entonces si existe pero es false entonces devuelve false, total, usando la opción 1 se resuelve!

            var rowFieldValue=selectedRow[actionDefinition.apiParams[i].dataArrName];
            if (actionDefinition.apiParams[i].paramName!=undefined && rowFieldValue!=undefined){

**Comment by FranGomezVenegas** [comment]
Aplicado tanto a aire como a agua
