### ISSUE TITLE
FE AIRE - Desviaciones. Al crear  una investigación sería optimo que se adjuntara automáticamente a la investigación creada.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#572]

**Comment by FranGomezVenegas** [comment]
La lógica estaba bien, lo que pasaba es que en la tabla de auditoría para eventos de investigaciones se añadió el campo reason (razón de la acción) pero no existía ni en em-demo-a ni en proc-deploy y al intentar hacer esta auditoría al crear la investigación no podía y no continuaba con la inserción del objeto, al añadir el campo se ha resuelto el problema, sin cambios en la lógica, solo a nivel de bdd.

**Comment by Joelsn** [comment]
funciona perfecto!
