### ISSUE TITLE
Al Cancelar el diálogo de Decisión, nos aparece el siguiente error el mismo error de  Uncaught TypeError: Cannot read property 'length' of undefined, parece que el error está en la linea functions-env-monit.js:252

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#573]
![image](https://user-images.githubusercontent.com/81186702/124182953-d73e8080-dab7-11eb-8bc3-cf4910d3f8e0.png)

**Comment by FranGomezVenegas** [comment]
Se ha solucionado. 
![image](https://user-images.githubusercontent.com/26067165/124287908-d9a0e900-db50-11eb-9049-8be6bf8fcbee.png)

El tema es que la función dialogClosedInvestigationDecision() es llamada por cualquier botón de Aceptar/Cancelar/Cerrar que aparezca en el diálogo. Pero sabemos si ha pulsado un botón u otro por el atributo dialogState.
El tema está en que si el dialogState es canceled entonces no debe hacer nada, es decir, no debe ejecutar esta acción porque la acción solo se debe ejecutar al pulsar el botón de Aceptar.

Se pone en Quarantine porque cuando hagamos el refactor del frontend es importante asegurar una buena gestión de este tema de los botones y las acciones.

**Comment by Joelsn** [comment]
No la he cerrado porque la pantalla por ahora no está funcionando, en cuando vuelva a la normalidad lo compruebo 100%

**Comment by FranGomezVenegas** [comment]
Ya funciona ...

**Comment by Joelsn** [comment]
funciona perfect
