### ISSUE TITLE
AGUA FE - FQ-Ensayos pendiente revisión, Sale el error Uncaught (in promise) TypeError: Cannot read property 'toastErrorMessageWithApiResponse' of undefined cuando le damos al botón auditoría pero sólo da error cuando antes le hemos dado al botón de Revisar análisis, este problema no es bloqueante en principio. 

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#576]
![image](https://user-images.githubusercontent.com/81186702/124308020-eb8e8600-db68-11eb-8378-afc5fed9c17e.png)

**Comment by FranGomezVenegas** [comment]
Ya lo he pillado! Era un problema de backend, se debe limpiar procReqInstance antes de llamar al método que devuelve el error porque en este caso no ejecuta la sección finally, que es la que se encarga de limpiar procReqInstance ..
