### ISSUE TITLE
AGUA FE - Al darle al botón de mostrar la evaluación de la muestra, nos vuelve a salirel error de Uncaught TypeError: Cannot read property 'message_es' of undefined, como en el caso de la incubadora aunque nos dice que es en  debounce.js:160

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#577]
![image](https://user-images.githubusercontent.com/81186702/124309949-cbac9180-db6b-11eb-82c7-9df22c9dbe0a.png)

**Comment by FranGomezVenegas** [comment]
Resuelto: 
    getItemValue(flddetail, item){    
        if (flddetail.name=='locking_reason'){
            if (this.selectedLanguage=="en"){
                if(item.locking_reason && item.locking_reason.message_en){return item.locking_reason.message_en;
                }else{return '';}
            }
            if (this.selectedLanguage=="es"){
                if(item.locking_reason && item.locking_reason.message_es){return item.locking_reason.message_es;
                }else{return '';}
            }
        }    
        if (flddetail.name=='spec_rule'){
            return this.getSpecRule(item);
        }
        return item[flddetail.name];
    }

**Comment by Joelsn** [comment]
Sigue dando el mismo mensaje de error, a ti ya no te da?

**Comment by FranGomezVenegas** [comment]
Parece que con 'la nueva pantalla' de entrada de resultados no sucede. He intentado reproducir la situación y no lo he conseguido, pruebalo de nuevo con este nuevo src y a ver qué tal ...
