### ISSUE TITLE
Si por ejemplo una muestra tuvo un resultado fuera de rango en FQ y está bloqueada, En el Area MB debería salir un icono que nos de un mensaje avisando de que hay un ensayo/resultado FQ en Out y por ese motivo se bloquea toda la muestra. Esta funcionalidad es necesaria para la trazabilidad de comunicación entre áreas de una empresa

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#583]

**Comment by FranGomezVenegas** [comment]
FQ yMB son testing group, por ende, son grupos de ensayos .... la muestra no es ni FQ ni MB, son los ensayos los que son FQ o MB .... :) Se entienden lo que quieres decir pero no cojas malos hábitos ... :)

**Comment by FranGomezVenegas** [comment]
Al final no es así, sólo se bloquea el resultado que estuvo OUT, el resto de ensayos quedan 'desbloqueados' y se pueden continuar ... eso si ... la revisar el ensayo y la muestra, si la investigación no está cerrada entonces no debe permitir realizar la revisión
