### ISSUE TITLE
FE AGUA - Muestras FQ - Al darle al botón actualizar nos sale un mensaje de que no se encuentra el archivo Sampleinprogress.png. La acción de actualizar si que funciona.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#587]
![image](https://user-images.githubusercontent.com/81186702/125256615-e4037580-e2fc-11eb-9c7a-adb785030284.png)

**Comment by FranGomezVenegas** [comment]
Porque te faltaban las imagenes, al tener un nuevo src ya debes tenerlas ... compruebalo
