### ISSUE TITLE
El programa aparece a la primera, pero no siempre carga los elementos, en consola nos da un mensaje rojo que nos dice:  index is not defined

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#588]
![image](https://user-images.githubusercontent.com/81186702/125309648-3612be00-e332-11eb-878c-65a06e47ed50.png)

**Comment by FranGomezVenegas** [comment]
El problema es que el settings aún no tiene el atributo de tabla con nombre tableHdrFlds.
![image](https://user-images.githubusercontent.com/26067165/125366053-a4c53b00-e375-11eb-83c2-0bb4bf1dc2c6.png)
