### ISSUE TITLE
Cuando inicias sesión después de haber cerrado sesión con un roll (por ejemplo coordinador), aparece seleccionado el roll (coordinador) y no te deja entrar.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#589]
![image](https://user-images.githubusercontent.com/81186702/125335720-294f9380-e34d-11eb-9490-54c4744e6926.png)

**Comment by FranGomezVenegas** [comment]
En realidad, es platform-login quien debe resetearlo, hasta ahora sólo conseguía resetear user y password pero role por ser tipo lista no podía ... pero ya ... SI! :)

Al añadir el método a field-list, que funcione! ;)

![image](https://user-images.githubusercontent.com/26067165/125703318-fe383432-1ed7-4b95-9da4-e5356cdecbd6.png)

![image](https://user-images.githubusercontent.com/26067165/125703351-301dfc06-26ec-4eed-bea8-284933e67f43.png)

**Comment by Joelsn** [comment]
perfecto!!1
