### ISSUE TITLE
En Program Límits, estaría bien que la parte de Método, análisis, parámetro y método y versión fuese bilingüe

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#591]
![image](https://user-images.githubusercontent.com/81186702/126309621-c5bd986c-de59-4769-ae31-d6482b0b1a26.png)

**Comment by FranGomezVenegas** [comment]
El backend 'abastece' de traducciones pero no todo, entonces el frontend debe emplear su 'motor de traducciones' propio para resolver esta problemática. Esto es así porque no podemos traducir 'todo' el modelo de datos y todos los literales de frontend ... 

Cada procInstanceName , en 03config, tiene la clase tableFieldLabel en el archivo tablefield_labels y este los métodos para cada objetivo, el ejemplo a seguir es este:

![image](https://user-images.githubusercontent.com/26067165/126567609-3101e6ae-70aa-4a8f-9153-4e6d227bbb3b.png)

Para cada entidad se define su estructura de datos, el ejemplo de los límites es el siguiente:
![image](https://user-images.githubusercontent.com/26067165/126567682-415e6d4d-e66e-45b7-8f9d-05840ffa887d.png)

**Comment by Joelsn** [comment]
buenisima!!
