### ISSUE TITLE
Se realiza la auditoría de la prueba 45 y a la hora de entrar resultados nos da el mensaje For the sample 45 there are still pending audit records for revision in procedure proc-deploy. aparte de bloquearnos la acción, solo aparece en inglés

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#594]
![image](https://user-images.githubusercontent.com/81186702/126628729-8f5940d9-ec67-4836-b572-b2e3f1c107dd.png)

**Comment by FranGomezVenegas** [comment]
La lógica para hacer que las subacciones de una acción de auditoría no se requiera revisar tenía una incidencia, se ha resuelto.
