### ISSUE TITLE
FE - AIRE Se crea una investigación con una muestra y se crea efectivamente, una vez realizada esta acción se apreta otra vez a crear una investigación sin acción correctiva y crea investigación. No debería permitir crear una investigación sin Acción correctiva.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#597]

**Comment by FranGomezVenegas** [comment]
Cierto, el código era 'muy feliciano' y creaba la investigación se pudiera añadir el objeto o no (porque si el objeto ya estaba en una investigación entonces no lo agregaba, pero la investigación ya estaba creada, por eso se creaban investigaciones vacías). Se va a hacer un check más sofisticado para evitar esas situaciones ....

**Comment by FranGomezVenegas** [comment]
Vinculado a guión de pruebas "Crear investigaciones"

**Comment by Joelsn** [comment]
1- se intenta crear una investigación sin muestra y nos sale el mensaje de que se debe de tener una muestra seleccionada
2- Se intenta crear una investigación con muestra y vemos que no llegan los mensajes del BE ( mensajes azul ssin contenido), miramos el inspector y se hacen dos llamadas:
·  la 1ª llamada hacia NEW_INVESTIGATION sin mensaje de respuesta.
· la 2ª llamada hacia INVESTIGATION_RESULTS_PENDING_DECISION Con respuesta aparentemente correcta ( foto )
![image](https://user-images.githubusercontent.com/81186702/135048576-d493c894-6364-4bd2-bfec-c2c30137beb4.png)
