### ISSUE TITLE
FE - Pendientes de Lectura de PL. Cuando se abre Entrar resultados y no se escribe ninguno, y se intenta aplicar en la siguiente muestra, aparece el ID de la anterior

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#603]
{"message_en":"The record select  result_id, test_id, sample_id, status, status_previous, analysis, method_name, method_version, replica, param_name, param_type, mandatory, requires_limit, raw_value, raw_value_num, pretty_value, entered_on, entered_by, reentered, spec_eval, spec_eval_detail, uom, uom_conversion_mode, aliquot_id, subaliquot_id, sample_config_code, sample_status, current_stage, program_name, sampling_date, shift, area, location_name, production_lot, program_day_id, program_day_date, sample_analysis_status, sample_analysis_ready_for_revision, testing_group, logged_on, limit_id, sampler, sampler_area, ready_for_revision, spec_code, spec_config_version, spec_variation_name, analysis_spec_limits, method_name_spec_limits, method_version_spec_limits, parameter, rule_type, rule_variables, uom_spec_limits, uom_conversion_mode_spec_limits, min_val_allowed, max_val_allowed, min_allowed_strict, max_allowed_strict, min_undetermined, max_undetermined, min_undet_strict, max_undet_strict, has_pre_invest, pre_invest_id, has_invest, invest_id, invest_object_id, sample_id, test_id, result_id, param_name, limit_id from \"em-demo-a-data\".\"sample_analysis_result_with_spec_limits\"   where sample_id=?   Order By test_id, result_id does not exist in table [1372] in procedure \"em-demo-a-data\".","is_error":true,"diagnostic":"LABPLANET_FALSE","message_es":"The record select  result_id, test_id, sample_id, status, status_previous, analysis, method_name, method_version, replica, param_name, param_type, mandatory, requires_limit, raw_value, raw_value_num, pretty_value, entered_on, entered_by, reentered, spec_eval, spec_eval_detail, uom, uom_conversion_mode, aliquot_id, subaliquot_id, sample_config_code, sample_status, current_stage, program_name, sampling_date, shift, area, location_name, production_lot, program_day_id, program_day_date, sample_analysis_status, sample_analysis_ready_for_revision, testing_group, logged_on, limit_id, sampler, sampler_area, ready_for_revision, spec_code, spec_config_version, spec_variation_name, analysis_spec_limits, method_name_spec_limits, method_version_spec_limits, parameter, rule_type, rule_variables, uom_spec_limits, uom_conversion_mode_spec_limits, min_val_allowed, max_val_allowed, min_allowed_strict, max_allowed_strict, min_undetermined, max_undetermined, min_undet_strict, max_undet_strict, has_pre_invest, pre_invest_id, has_invest, invest_id, invest_object_id, sample_id, test_id, result_id, param_name, limit_id from \"em-demo-a-data\".\"sample_analysis_result_with_spec_limits\"   where sample_id=?   Order By test_id, result_id does not exist in table [1372] in procedure \"em-demo-a-data\"."}

**Comment by FranGomezVenegas** [comment]
La solución es relativamente sencilla, en caso de que "todo va bien" devuelve un código 200, entonces se ejecuta el 1r dispatch de la foto, linea 236, esto ya estaba.
En caso de fallo, lineas 240 y 246 entonces además de mostrar el mensaje al usuario (ya estaba) debe vaciar el contenido de la ejecución anterior para  al menos que no permita hacer una acción sobre otra muestra ... se ha añadido al de audit también, se debería añadir esta lógica a cualquier llamada de endpoint. Se ha añadido tanto a agua como a aire. para estas dos acciones.

![image](https://user-images.githubusercontent.com/26067165/128263853-079e1263-2354-47ed-812a-03c05e890e9f.png)

**Comment by Joelsn** [comment]
perfecto, comprobado y funciona1!!
