### ISSUE TITLE
Cuando vamos a crear una incidencia, el botón de crear no produce la acción esperada, pareciera que algo del methodName no acaba de estar definido

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#609]
![image](https://user-images.githubusercontent.com/81186702/130211895-e78f9cf9-080f-4a2f-95c9-67dcfb79245f.png)
![image](https://user-images.githubusercontent.com/81186702/130212593-f638cdd3-648a-4ae1-aaa6-5a5a3b1d939a.png)

**Comment by FranGomezVenegas** [comment]
Está en la nueva plataforma
