### ISSUE TITLE
Diálogo de introducción de datos no se traduce al español

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#610]
![image](https://user-images.githubusercontent.com/81186702/130226341-9e35a1e1-b8a1-49cd-a3b6-1b83408aa12b.png)

**Comment by FranGomezVenegas** [comment]
Si se traducen las etiquetas, lo que no es traducible es el contenido de las celdas, de momento. Lo vamos a abordar pero en el futuro, de momento se acepta que no sea traducible este tipo de datos, lo dijo Karl.
