### ISSUE TITLE
Nos ocurre el mismo caso que en el aire, la tabla de limites no se traduce al 100% en ingles

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#613]
![image](https://user-images.githubusercontent.com/81186702/130615473-f8718153-c525-4eda-ba7a-0e3783c730bb.png)

**Comment by FranGomezVenegas** [comment]
Lo mismo que #610 . Traducir la data maestra no se contempla ... de momento

**Comment by Joelsn** [comment]
Cierro incidencia porque se ha comprobado que se traduzca en el FE nuevo:
![image](https://user-images.githubusercontent.com/81186702/150114061-c4d59712-1946-4900-a7af-a7f3df4c448c.png)
