### ISSUE TITLE
Se nos ha colado un mensaje de la API sin traducir!! habria que traducirlo a : Sampling date is mandatory for sample ...

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#615]
![image](https://user-images.githubusercontent.com/81186702/130787637-fa6ef59f-3218-4623-afa2-ee546e3efe5a.png)
![image](https://user-images.githubusercontent.com/81186702/130787911-918985bf-109b-4829-8e7d-9359229ff897.png)

**Comment by FranGomezVenegas** [comment]
¿Ha sido al intentar mover de estado? Es importante que cuando crees una incidencia des la información para poder entender la situación y no solo el resultado.

**Comment by FranGomezVenegas** [comment]
![image](https://user-images.githubusercontent.com/26067165/133936853-67af035e-bb14-45ff-8d0b-68353dde7f01.png)

Resuelto gracias al nuevo mecanismo de notificaciones ...
