### ISSUE TITLE
No se nos está cargando el diálogo de lectura de placas, al abrirse nos da: Respuesta de error devuelta por la API undefined. En texto especifico la pregunta y la respuesta:

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#621]
![image](https://user-images.githubusercontent.com/81186702/131724686-34f119e2-dd17-480a-94d0-82451e5c2048.png)
La pregunta parece que se está ejecutando correctamente.

Aqui ajunto la respuesta obtenida:

{"message_en":"The database returned error: res is set to null Query: select  result_id, test_id, sample_id, status, status_previous, analysis, method_name, method_version, replica, param_name, param_type, mandatory, requires_limit, raw_value, raw_value_num, pretty_value, entered_on, entered_by, reentered, spec_eval, spec_eval_detail, uom, uom_conversion_mode, aliquot_id, subaliquot_id, sample_config_code, sample_status, current_stage, program_name, sampling_date, shift, area, location_name, production_lot, program_day_id, program_day_date, sample_analysis_status, sample_analysis_ready_for_revision, testing_group, logged_on, limit_id, sampler, sampler_area, ready_for_revision, spec_code, spec_config_version, spec_variation_name, analysis_spec_limits, method_name_spec_limits, method_version_spec_limits, parameter, rule_type, rule_variables, uom_spec_limits, uom_conversion_mode_spec_limits, min_val_allowed, max_val_allowed, min_allowed_strict, max_allowed_strict, min_undetermined, max_undetermined, min_undet_strict, max_undet_strict, has_pre_invest, pre_invest_id, has_invest, invest_id, invest_object_id, sample_reviewer, test_reviewer, sample_id, test_id, result_id, param_name, limit_id from \"em-demo-a-data\".\"sample_analysis_result_with_spec_limits\"   where sample_id=?   Order By test_id, result_id Values: [1399].","is_error":true,"diagnostic":"LABPLANET_FALSE","message_es":"The database returned error: res is set to null Query: select  result_id, test_id, sample_id, status, status_previous, analysis, method_name, method_version, replica, param_name, param_type, mandatory, requires_limit, raw_value, raw_value_num, pretty_value, entered_on, entered_by, reentered, spec_eval, spec_eval_detail, uom, uom_conversion_mode, aliquot_id, subaliquot_id, sample_config_code, sample_status, current_stage, program_name, sampling_date, shift, area, location_name, production_lot, program_day_id, program_day_date, sample_analysis_status, sample_analysis_ready_for_revision, testing_group, logged_on, limit_id, sampler, sampler_area, ready_for_revision, spec_code, spec_config_version, spec_variation_name, analysis_spec_limits, method_name_spec_limits, method_version_spec_limits, parameter, rule_type, rule_variables, uom_spec_limits, uom_conversion_mode_spec_limits, min_val_allowed, max_val_allowed, min_allowed_strict, max_allowed_strict, min_undetermined, max_undetermined, min_undet_strict, max_undet_strict, has_pre_invest, pre_invest_id, has_invest, invest_id, invest_object_id, sample_reviewer, test_reviewer, sample_id, test_id, result_id, param_name, limit_id from \"em-demo-a-data\".\"sample_analysis_result_with_spec_limits\"   where sample_id=?   Order By test_id, result_id Values: [1399]."}

**Comment by FranGomezVenegas** [comment]
Mismo problema y misma solución que la anterior ...
