### ISSUE TITLE
En Entradas de Resultados de FQ y MB tampoco se nos está ejecutando el diálogo de entrada de resultados, a continuación dejo tanto la pregunta como la respuesta

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#622]
Pregunta en pantalla Entrada de Resultados MB
![image](https://user-images.githubusercontent.com/81186702/131725133-a4eab3f4-89bf-4722-8044-072d7f2baa12.png)

Respuesta:
{"message_en":"The database returned error: res is set to null Query: select  result_id, test_id, sample_id, status, status_previous, analysis, method_name, method_version, replica, param_name, param_type, mandatory, requires_limit, raw_value, raw_value_num, pretty_value, entered_on, entered_by, reentered, spec_eval, spec_eval_detail, uom, uom_conversion_mode, aliquot_id, subaliquot_id, sample_config_code, sample_status, current_stage, program_name, sampling_date, shift, area, location_name, production_lot, program_day_id, program_day_date, sample_analysis_status, sample_analysis_ready_for_revision, testing_group, logged_on, limit_id, sampler, sampler_area, ready_for_revision, spec_code, spec_config_version, spec_variation_name, analysis_spec_limits, method_name_spec_limits, method_version_spec_limits, parameter, rule_type, rule_variables, uom_spec_limits, uom_conversion_mode_spec_limits, min_val_allowed, max_val_allowed, min_allowed_strict, max_allowed_strict, min_undetermined, max_undetermined, min_undet_strict, max_undet_strict, has_pre_invest, pre_invest_id, has_invest, invest_id, invest_object_id, sample_reviewer, test_reviewer, sample_id, test_id, result_id, param_name, limit_id from \"proc-deploy-data\".\"sample_analysis_result_with_spec_limits\"   where sample_id=?  and testing_group=?  and status not in (?)  Order By test_id, result_id Values: [48, MB, REVIEWED].","is_error":true,"diagnostic":"LABPLANET_FALSE","message_es":"The database returned error: res is set to null Query: select  result_id, test_id, sample_id, status, status_previous, analysis, method_name, method_version, replica, param_name, param_type, mandatory, requires_limit, raw_value, raw_value_num, pretty_value, entered_on, entered_by, reentered, spec_eval, spec_eval_detail, uom, uom_conversion_mode, aliquot_id, subaliquot_id, sample_config_code, sample_status, current_stage, program_name, sampling_date, shift, area, location_name, production_lot, program_day_id, program_day_date, sample_analysis_status, sample_analysis_ready_for_revision, testing_group, logged_on, limit_id, sampler, sampler_area, ready_for_revision, spec_code, spec_config_version, spec_variation_name, analysis_spec_limits, method_name_spec_limits, method_version_spec_limits, parameter, rule_type, rule_variables, uom_spec_limits, uom_conversion_mode_spec_limits, min_val_allowed, max_val_allowed, min_allowed_strict, max_allowed_strict, min_undetermined, max_undetermined, min_undet_strict, max_undet_strict, has_pre_invest, pre_invest_id, has_invest, invest_id, invest_object_id, sample_reviewer, test_reviewer, sample_id, test_id, result_id, param_name, limit_id from \"proc-deploy-data\".\"sample_analysis_result_with_spec_limits\"   where sample_id=?  and testing_group=?  and status not in (?)  Order By test_id, result_id Values: [48, MB, REVIEWED]."}

**Comment by FranGomezVenegas** [comment]
Prueba de nuevo, un cambio para incluir el revisor en la consulta ... pero no estaba físicamente ....ahora ya!
