### ISSUE TITLE
Al crear una muestra desde Registrar muestra no carga en Lote, si la muestra se crea desde Maps si que carga todos los Lotes disponibles - IMPORTANTE -> Program Sampling Point está repetido dos veces en la pantalla de Login New Samples

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#623]
Pregunta desde pantalla de Crear muestra:
actionName: LOGSAMPLE
programName: LlenadoVialesFA2018
locationName: V03F
sampleTemplate: program_smp_template
sampleTemplateVersion: 1
numSamplesToLog: 1
finalToken: eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hXSIsInR5cCI6IkpXVCIsImFwcFNlc3Npb25JZCI6IjE2OTk3IiwiYXBwU2Vzc2lvblN0YXJ0ZWREYXRlIjoiVHVlIFNlcCAwNyAxMToxMjo1MCBVVEMgMjAyMSIsInVzZXJSb2xlIjoiY29vcmRpbmF0b3IiLCJhbGciOiJIUzI1NiIsImludGVybmFsVXNlcklEIjoiMTIifQ.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.dIbKY28JsNts-MFVbBH9348QdfhYpzi4SSv57ruaZp0
procInstanceName: em-demo-a
dbName: labplanet

Respuesta
{"related_objects":[{"object_type":"sample","object_name":"1551","schema_name":"\"em-demo-a-data\"","table_name":"sample"}],"message_en":"Logged sample 1551 with success.","is_error":false,"diagnostic":"LABPLANET_TRUE","category":"ENVMONSAMPLE","message_es":"Registrada muestra 1551 correctamente."}

Pregunta desde pantalla Programs pestaña Sampling Points Maps
actionName: LOGSAMPLE
programName: LlenadoVialesFA2018
locationName: C01-grB
sampleTemplate: program_smp_template
sampleTemplateVersion: 1
numSamplesToLog: 1
finalToken: eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hXSIsInR5cCI6IkpXVCIsImFwcFNlc3Npb25JZCI6IjE2OTk3IiwiYXBwU2Vzc2lvblN0YXJ0ZWREYXRlIjoiVHVlIFNlcCAwNyAxMToxMjo1MCBVVEMgMjAyMSIsInVzZXJSb2xlIjoiY29vcmRpbmF0b3IiLCJhbGciOiJIUzI1NiIsImludGVybmFsVXNlcklEIjoiMTIifQ.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.dIbKY28JsNts-MFVbBH9348QdfhYpzi4SSv57ruaZp0
procInstanceName: em-demo-a
dbName: labplanet

Respuesta:
{"related_objects":[{"object_type":"sample","object_name":"1553","schema_name":"\"em-demo-a-data\"","table_name":"sample"}],"message_en":"Logged sample 1553 with success.","is_error":false,"diagnostic":"LABPLANET_TRUE","category":"ENVMONSAMPLE","message_es":"Registrada muestra 1553 correctamente."}

**Comment by FranGomezVenegas** [comment]
Esta pantalla usa el programSelector que solo cargaba los programas, ahora hay que hacer uqe tb cargue los lotes de producción, añadiendo lo siguiente:
![image](https://user-images.githubusercontent.com/26067165/134495632-e06eb010-f7bb-4847-9d80-07b9854bb599.png)

![image](https://user-images.githubusercontent.com/26067165/134495694-b3a0e05d-0016-425a-a943-ac22e4c20aef.png)

Aplicado tanto en aire como agua

**Comment by Joelsn** [comment]
Se comprueba en aire y agua
Aire: 
1-  Se crea muestra y aparecen todos los Lotes de manera correcta
2- Se crea un nuevo Lote correctamente y se abre diálogo de crear muestra, no aparece el nuevo Lote Creado
3- Se actualiza la tabla de crear muestra y se abre diálogo de crear muestra, no aparece el Lote creado.
4- Nos dirigimos a Programas, crear muestras y aparece el nuevo Lote creado al crear muestra
5- Se repite proceso de crear un nuevo lote, se va a Programas crear muestra y no aparece el Lote creado
6- Se refresca pantalla, logeamos de nuevo, creamos muestra y aparece el Lote Creado
Conclusion: Al crear una muestra con un lote nuevo, aparece al rato de haberlo creado, no se donde se refresca la petición de los lotes creados, termina apareciendo pero en un tiempo algo " random ", se seguirán haciendo pruebas. Algo a tener en cuenta es que sigue apareciendo repetida la pantalla de crear muestra en la pestaña de login sample, podría ser que produzca problemas a la hora realizar la consulta? ( ver foto )
![image](https://user-images.githubusercontent.com/81186702/134639642-4faf6716-fde4-4ed8-9387-dd190622c5bf.png)


Agua:
1- Se abre diálogo de crear muestra en pantalla de Login New sample y se  cargan los Lotes
2- Se crea un Lote y se comprueba si sale en la pantalla de Login New sample. No aparece.
3- Nos dirigimos a Programs Sampling Points y si aparece el Lote creado.
4- Nos dirigimos a pantalla de Login New sample y sigue sin aparecer el Lote creado
5- Creamos un nuevo lote y no aparece en Login New Sample, Nos dirigimos a Programs Sample Point, abrimos diálogo y no aparece el Lote creado
6- Se actualiza la página y se abre diálogo de crear muestra en pantalla de Login New Sample y aparece los Lotes creados. Se realiza lo mismo en Programs Sampling Points y aparecen todos los Lotes creados.

Conclusion: la forma mas fiable para que salga la información de los Lotes al crear una muestra es actualizando la página, si que es verdad que al abrir los programas e ir a program sampling point a aparecido en algunos casos, pero parece que no se consigue actualizar a la vez que se crea el lote y menos en la pantalla de creación de muestras. ¿Habría que buscar una forma para que cada vez que el diálogo de crear muestra se abra se actualice actualice la información haciendo una llamada?

**Comment by FranGomezVenegas** [comment]
Se ha encontrado el motivo, el elemento se debe reiniciar para que se pueda reconstruir el contenido (cosas de javascript): 

    createProductionLotsList(){
        //console.log('createProductionLotsList', 'this.productionLotsList', this.productionLotsList);
        var i;
        **_this.productionLotsList=[{"keyName":'', "keyValue_en":'',"keyValue_es":''}];_**
        for (i = 0; i < this.activeProductionLots.length; i++) {
            //console.log(this.activeProductionLots[i].lot_name);
            var newElement=[{"keyName":'', "keyValue_en":'',"keyValue_es":''}];
            newElement.keyName=this.activeProductionLots[i].lot_name;
            newElement.keyValue_en=this.activeProductionLots[i].lot_name;
            newElement.keyValue_es=this.activeProductionLots[i].lot_name;
            this.productionLotsList[i+1]=newElement;
        }   
        //console.log(this.productionLotsList);     
    }

**Comment by Joelsn** [comment]
Se crean muestras tanto en aire y agua y funciona al 100%, cierro incidencia.
