### ISSUE TITLE
IDEA: Que aparezca el rango de Limite al introducir un resultado "In"

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#625]
![image](https://user-images.githubusercontent.com/81186702/132350826-34612922-5d82-4c51-a3f1-3e3c340b69fc.png)

**Comment by FranGomezVenegas** [comment]
Se ha cambiado el campo para que sea spec_rule_wirh_detail. 

![image](https://user-images.githubusercontent.com/26067165/134422298-c368d099-08be-43f4-85bc-40627fd83d26.png)

Ahora para el IN ya aparece:
![image](https://user-images.githubusercontent.com/26067165/134422428-63a863b4-eba2-4fa2-b889-1a03aebed195.png)

Hasta para un resultado no entrado ya aparecerá la regla:
![image](https://user-images.githubusercontent.com/26067165/134422165-ad6ed793-0742-4f21-874f-419833a6b847.png)
