### ISSUE TITLE
En Lectura de Placas Hay que añadir la función: Cuando se realice un reenter debe obligar a una justificación del cambio

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#631]
*Nota para joel: Cuando se realice volver a grabar video Lectura de Placas explicando esta función

**Comment by FranGomezVenegas** [comment]
A nivel de backend ya está hecho. Se ha creado un endpoint llamado REENTERRESULT,  además se ha añadido la lógica en ENTERRESULT para que compruebe si este resultado ya fue entrado previamente y de ser así tratará la acción como REENTERRESULT. Si se añade en la lista de las acciones que requiere justificación entonces el backend no procederá sin razón del cambio. 
Falta adaptar el FrontEnd para que haga la gestión.
