### ISSUE TITLE
SetSamplingDate Vs ChangeSamplingDate

### ISSUE THREAD

**Issue by FranGomezVenegas** [FranGomezVenegas/LP#633]
La acción SetSamplingDate solo permite entrar la primera fecha de muestreo y si se ejecuta nuevamente una vez se entró la primera fecha debe dar mensaje de error indicando que para cambiar una fecha se debe usar ChangeSamplingDate.

De la misma forma, ChangeSamplingDate debe permitir cambiar una fecha previamente entrada pero nunca debe permitir añadir la primera fecha de muestreo.

De esta forma, a modo de resumen, Set es para la 1ª entrada y Change es para cambiarla tantas veces como se desee (quedará auditado cada cambio y a futuro pedirá motivo del cambio).

**Comment by FranGomezVenegas** [comment]
![image](https://user-images.githubusercontent.com/26067165/132421786-2d0a1da3-ffe7-4efa-a382-27cc431d9383.png)

**Comment by Joelsn** [comment]
perfecto, se valida porque veo que has hecho la prueba y funciona correctamente
