### ISSUE TITLE
En la pantalla de Incubación se debería poder saber si la incubadora esta locked y no permite hacer el inicio de Tanda (por ejemplo, por si la incubadora esta fuera de la temperatura minima/maxima )

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#642]

**Comment by FranGomezVenegas** [comment]
![image](https://user-images.githubusercontent.com/26067165/135149782-695dbc81-84f2-4687-80f1-59c5f40b18df.png)
y la razón en la última columna:
![image](https://user-images.githubusercontent.com/26067165/135150333-061b6a8e-4be9-4446-a7ef-979547e3658e.png)

La consulta nos da la informacion de si está locked y la reason, entonces si está locked usa otro icono que los dos actuales ...

**Comment by Joelsn** [comment]
valido porque parece estar solucionado!!!
