### ISSUE TITLE
When we log in and the first thing we do is create a sample on the create samples screen, the Lot does not appear. If it is created from Programs it seems that the list is loaded and the Batches already appear.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#656]
![image](https://user-images.githubusercontent.com/81186702/136523429-d1c0479c-a5c9-48a5-b2d0-4cd5170ebcbb.png)
![image](https://user-images.githubusercontent.com/81186702/136523494-6eb2920c-c133-4dda-845e-4754bd0a9ddc.png)

**Comment by FranGomezVenegas** [comment]
Ya funciona!
