### ISSUE TITLE
Proc-deploy Script 10 ScriptStep 21, 23 Relacionados con Testing Group. nos devuelve el mensaje: Syntaxis:LABPLANET_TRUE. Code:RecordUpdated. Message:Updated sample_revision_testing_group records by the filter [268, FQ] in schema "proc-deploy-data_testing". El argumento de la regla de negocio es: revisión manual de análisis de test y sample pero auto en test group

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#678]

**Comment by Joelsn** [comment]
Se reabre porque sigue apareciendo problema con el autoapprove de Testing Group, 
Syntaxis:LABPLANET_TRUE. Code:RecordUpdated. Message:Updated sample_revision_testing_group records by the filter [588, FQ] in schema "proc-deploy-data_testing".

La norma de autoapprove está activa para Testing Group, así que la syntaxis debería dar: LABPLANET_FALSE, y nos está devolviendo LABPLANET_TRUE.

**Comment by FranGomezVenegas** [comment]
Corregido, ahora lo que sucede es que el paso 21 si da false porque testingroup se autoaprueba. Entonces los dos testinggroup ya estan autoaprobados y el paso 22 ya sí puede hacer reviewsample, entonces el resto de pasos 'sobran' o al menos deben dar LABPLANET_FALSE

**Comment by Joelsn** [comment]
Testing Group se ha arreglado perfecto, ahora aparece el problema de que la regla en reviewsample NO tiene auttoapprove activado. TESTING 10 STEP 22,24
En la siguiente imagen vemos que en el primer reviewsample (22) nos dice que es LABPLANET_TRUE, pero no debería hacerlo ya que el testing group no está revisado, así que no debería permitir hacer el reviewsample
En el último paso (24) vemos que nos pide FALSE como si estuviese el auttoapprove estuviese activado.

![image](https://user-images.githubusercontent.com/81186702/140484855-4a876958-526c-471c-a190-1915e282de4c.png)
![image](https://user-images.githubusercontent.com/81186702/140484416-0dbbaed8-cf49-431b-9bc2-c9694265d267.png)

**Comment by FranGomezVenegas** [comment]
**"En la siguiente imagen vemos que en el primer reviewsample (22) nos dice que es LABPLANET_TRUE, pero no debería hacerlo ya que el testing group no está revisado"** --> Si que está revisado porque lo hace el autoapprove 
**" así que no debería permitir hacer el reviewsample"** --> si debería permitirlo entonces.
