### ISSUE TITLE
Se ha encontrado fallo de respuesta en Desviaciones en las acciones: Añadir Investigación, tomar decisión y cerrar la decisión. Se recibe respuesta de fallo al primer llamamiento, pero si se repite la acción termina dando resultado esperado. Añado respuestas que fallan.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#682]
**Respuesta Fallida Añadir a Investigación:**
{"message_en":"","is_error":true,"diagnostic":"LABPLANET_FALSE","message":"The action INVESTIGATION_RESULTS_PENDING_DECISION is not declared in the rule procedureActions for the procedure em-demo-a. The actions declared are [EMLOGSAMPLE, REENTERRESULT, ADD_ADHOC_SAMPLE_MICROORGANISM, GET_SAMPLE_RESULTS, GET_SAMPLE_INFO, REMOVE_SAMPLE_MICROORGANISM, PLATE_READING_NUMBER, CREATE_SAVED_QUERY, CLOSE_INVESTIGATION, ADD_INVEST_OBJECTS, NEW_INVESTIGATION, INVESTIGATION_CAPA_DECISION, EM_BATCH_INCUB_REMOVE, EM_LOGSAMPLE_SCHEDULER, PROD_LOT_DEACTIVATE, PROD_LOT_ACTIVATE, EM_BATCH_INCUB_MOVE_SMP, EM_BATCH_UPDATE_INFO, EM_BATCH_ASSIGN_INCUB, EM_BATCH_INCUB_START, EM_BATCH_INCUB_END, EM_BATCH_INCUB_REMOVE_SMP, EM_BATCH_INCUB_ADD_SMP, EM_BATCH_INCUB_CREATE, EM_INCUBATION_ADD_TEMP_READING, EM_INCUBATION_LAST_TEMP_READINGS, EM_INCUBATION_DEACTIVATE, EM_INCUBATION_ACTIVATE, EM_ACTIVATE_PRODUCTION_LOT, EM_DEACTIVATE_PRODUCTION_LOT, EM_NEW_PRODUCTION_LOT, SAMPLEAUDIT_SET_AUDIT_ID_REVIEWED, SETSAMPLINGDATE, ADD_SAMPLE_MICROORGANISM, INCUBATION2END, INCUBATION2START, SAMPLESTAGE_MOVETONEXT, SAMPLESTAGE_MOVETOPREVIOUS, CORRECTIVE_ACTION_COMPLETE, LOGSAMPLE, LOGALIQUOT, LOGSUBALIQUOT, RECEIVESAMPLE, SAMPLEANALYSISADD, TESTASSIGNMENT, ENTERRESULT, REVIEWRESULT, GETSAMPLEINFO, CHANGESAMPLINGDATE, SAMPLINGCOMMENTADD, SAMPLINGCOMMENTREMOVE, INCUBATIONSTART, INCUBATIONEND, CANCELRESULT, UNCANCELRESULT, UNREVIEWRESULT, COC_STARTCHANGE, COC_CONFIRMCHANGE, COC_ABORTCHANGE, RESULT_CHANGE_UOM].","message_es":""}

**Respuesta Fallida Decisión:**
 {"message_en":"","is_error":true,"diagnostic":"LABPLANET_FALSE","message":"The action OPEN_INVESTIGATIONS is not declared in the rule procedureActions for the procedure em-demo-a. The actions declared are [EMLOGSAMPLE, REENTERRESULT, ADD_ADHOC_SAMPLE_MICROORGANISM, GET_SAMPLE_RESULTS, GET_SAMPLE_INFO, REMOVE_SAMPLE_MICROORGANISM, PLATE_READING_NUMBER, CREATE_SAVED_QUERY, CLOSE_INVESTIGATION, ADD_INVEST_OBJECTS, NEW_INVESTIGATION, INVESTIGATION_CAPA_DECISION, EM_BATCH_INCUB_REMOVE, EM_LOGSAMPLE_SCHEDULER, PROD_LOT_DEACTIVATE, PROD_LOT_ACTIVATE, EM_BATCH_INCUB_MOVE_SMP, EM_BATCH_UPDATE_INFO, EM_BATCH_ASSIGN_INCUB, EM_BATCH_INCUB_START, EM_BATCH_INCUB_END, EM_BATCH_INCUB_REMOVE_SMP, EM_BATCH_INCUB_ADD_SMP, EM_BATCH_INCUB_CREATE, EM_INCUBATION_ADD_TEMP_READING, EM_INCUBATION_LAST_TEMP_READINGS, EM_INCUBATION_DEACTIVATE, EM_INCUBATION_ACTIVATE, EM_ACTIVATE_PRODUCTION_LOT, EM_DEACTIVATE_PRODUCTION_LOT, EM_NEW_PRODUCTION_LOT, SAMPLEAUDIT_SET_AUDIT_ID_REVIEWED, SETSAMPLINGDATE, ADD_SAMPLE_MICROORGANISM, INCUBATION2END, INCUBATION2START, SAMPLESTAGE_MOVETONEXT, SAMPLESTAGE_MOVETOPREVIOUS, CORRECTIVE_ACTION_COMPLETE, LOGSAMPLE, LOGALIQUOT, LOGSUBALIQUOT, RECEIVESAMPLE, SAMPLEANALYSISADD, TESTASSIGNMENT, ENTERRESULT, REVIEWRESULT, GETSAMPLEINFO, CHANGESAMPLINGDATE, SAMPLINGCOMMENTADD, SAMPLINGCOMMENTREMOVE, INCUBATIONSTART, INCUBATIONEND, CANCELRESULT, UNCANCELRESULT, UNREVIEWRESULT, COC_STARTCHANGE, COC_CONFIRMCHANGE, COC_ABORTCHANGE, RESULT_CHANGE_UOM].","message_es":""}

**Respuesta Fallida Cerrar Investigación:**
{"message_en":"","is_error":true,"diagnostic":"LABPLANET_FALSE","message":"The action OPEN_INVESTIGATIONS is not declared in the rule procedureActions for the procedure em-demo-a. The actions declared are [EMLOGSAMPLE, REENTERRESULT, ADD_ADHOC_SAMPLE_MICROORGANISM, GET_SAMPLE_RESULTS, GET_SAMPLE_INFO, REMOVE_SAMPLE_MICROORGANISM, PLATE_READING_NUMBER, CREATE_SAVED_QUERY, CLOSE_INVESTIGATION, ADD_INVEST_OBJECTS, NEW_INVESTIGATION, INVESTIGATION_CAPA_DECISION, EM_BATCH_INCUB_REMOVE, EM_LOGSAMPLE_SCHEDULER, PROD_LOT_DEACTIVATE, PROD_LOT_ACTIVATE, EM_BATCH_INCUB_MOVE_SMP, EM_BATCH_UPDATE_INFO, EM_BATCH_ASSIGN_INCUB, EM_BATCH_INCUB_START, EM_BATCH_INCUB_END, EM_BATCH_INCUB_REMOVE_SMP, EM_BATCH_INCUB_ADD_SMP, EM_BATCH_INCUB_CREATE, EM_INCUBATION_ADD_TEMP_READING, EM_INCUBATION_LAST_TEMP_READINGS, EM_INCUBATION_DEACTIVATE, EM_INCUBATION_ACTIVATE, EM_ACTIVATE_PRODUCTION_LOT, EM_DEACTIVATE_PRODUCTION_LOT, EM_NEW_PRODUCTION_LOT, SAMPLEAUDIT_SET_AUDIT_ID_REVIEWED, SETSAMPLINGDATE, ADD_SAMPLE_MICROORGANISM, INCUBATION2END, INCUBATION2START, SAMPLESTAGE_MOVETONEXT, SAMPLESTAGE_MOVETOPREVIOUS, CORRECTIVE_ACTION_COMPLETE, LOGSAMPLE, LOGALIQUOT, LOGSUBALIQUOT, RECEIVESAMPLE, SAMPLEANALYSISADD, TESTASSIGNMENT, ENTERRESULT, REVIEWRESULT, GETSAMPLEINFO, CHANGESAMPLINGDATE, SAMPLINGCOMMENTADD, SAMPLINGCOMMENTREMOVE, INCUBATIONSTART, INCUBATIONEND, CANCELRESULT, UNCANCELRESULT, UNREVIEWRESULT, COC_STARTCHANGE, COC_CONFIRMCHANGE, COC_ABORTCHANGE, RESULT_CHANGE_UOM].","message_es":""}

**Comment by FranGomezVenegas** [comment]
Añadi una cosa que es para acciones en estas consultas por error, ya está resuelto

**Comment by Joelsn** [comment]
Se a revisado y funciona bien!! pero en pestaña de Decisiones Pendientes no se recibe respuesta deseada: [{"program_corrective_action":"program corrective action not active!"}]

URL Endpoint:

http://51.75.202.142:8888/LabPLANET-API/frontend/InvestigationAPIfrontend?procInstanceName=em-demo-a&dbName=labplanet&actionName=INVESTIGATION_RESULTS_PENDING_DECISION&finalToken=eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hXSIsInR5cCI6IkpXVCIsImFwcFNlc3Npb25JZCI6IjE4MTczIiwiYXBwU2Vzc2lvblN0YXJ0ZWREYXRlIjoiVHVlIE5vdiAwMiAwODo1MjoyNyBVVEMgMjAyMSIsInVzZXJSb2xlIjoiY29vcmRpbmF0b3IiLCJhbGciOiJIUzI1NiIsImludGVybmFsVXNlcklEIjoiMTIifQ.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.RdNnPutgUYh8_OwhJYZNaRTDMP4G8Gn4DfHiUL2B9kw

**Comment by Joelsn** [comment]
Se revisa y se ve que Desviaciones Pendientes ya carga contenido, Pero volvemos a encontrar problemas en la pestaña de Pending Decision y la pestaña de Add to investigation. 
**Al crear Investigación** vemos que nos el FE nos devuelve mensaje rojo y al repetir la acción mensaje azul ( vacíos los dos), al mirar los dos EndPoints que actúan vemos que:
· NEW_INVESTIGATION: Sin Respuesta
· INVESTIGATION_RESULTS_PENDING_DECISION: is not declared in the rule procedureActions for the procedure em-demo-a

**Al intentar añadir a investigación** recibimos varios mensajes de API en rojo, no consiguiendo la acción en ninguno de ellos. las respuestas recibidas al realizar diferentes acciones son:
· ADD_INVEST_OBJECTS: 
- sample_analysis_result 1148 ya está presente en la investigación 198 (si así fuese debería desaparecer de la pantalla)
- "El registro <*1*> no existe en la tabla <*2*> en el proceso <*3*>."

**En la pestaña de Investigation**, encontramos los problemas tanto en **Decision y Close** vistos anteriormente, donde al realizar el proceso falla devolviendo mensaje desde la API pero no realizando la acción y al repetir el proceso si que realiza la acción devolviendo mensaje correcto.

En el caso de **Decision**
_Cuando falla,_ observamos que se realiza una unica respuesta al EndPoint INVESTIGATION_CAPA_DECISION. 
Respuesta  de la API al caso de fallo en Decisión:
- INVESTIGATION_CAPA_DECISION: The action OPEN_INVESTIGATIONS is not declared in the rule procedureActions for the procedure em-demo-a

_Cuando funciona_ observamos que responden correctamente los 2 EndPoints:
OPEN_INVESTIGATIONS
INVESTIGATION_CAPA_DECISION: "investigationDescisionTaken_success


En el caso de **Close**
_Cuando falla_, vemos que el problema radica en el mismo caso que en Decision
OPEN_INVESTIGATIONS: The action OPEN_INVESTIGATIONS is not declared in the rule procedureActions for the procedure em-demo-a

_Cuando funciona_ observamos que responden correctamente los 2 EndPoints:
OPEN_INVESTIGATIONS
CLOSE_INVESTIGATION,"message_en":"investigationClosed_success

**Comment by FranGomezVenegas** [comment]
Ya he encontrado el motivo, dejaba la sesion de Backend abierta y mezclaba endpoints, por eso menciona uno diferente al que invoca la llamada! Ahora ya sí que cierra la sesión de backend y resuelve el problema
