### ISSUE TITLE
La pantalla de Incidencias nos está devolviendo el mensaje : Response error from API undefined, ocurre al intentar aceptar cualquier tipo de acción sobre un diálogo (new incident, open incident, close incident, etc), pareciese que tiene que ver con el problema ocurrido en el nuevo FE

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#683]
Respuesta de la API:
{"message_en":"","is_error":true,"diagnostic":"LABPLANET_FALSE","message":"","message_es":""}

URL Endpoint:
http://51.75.202.142:8888/LabPLANET-API/app/IncidentAPI?finalToken=eyJ1c2VyREIiOiJ3YXRlciIsImVTaWduIjoiZWxvY28iLCJ1c2VyREJQYXNzd29yZCI6ImxvY28iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbcHJvYy1kZXBsb3ldIiwidHlwIjoiSldUIiwiYXBwU2Vzc2lvbklkIjoiMTgxNDUiLCJhcHBTZXNzaW9uU3RhcnRlZERhdGUiOiJGcmkgT2N0IDI5IDE1OjMzOjAwIFVUQyAyMDIxIiwidXNlclJvbGUiOiJjb29yZGluYXRvciIsImFsZyI6IkhTMjU2IiwiaW50ZXJuYWxVc2VySUQiOiI5In0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.Mr8RTRQuE98GnYqOPvl1DbChCMsr1cglwe4I00rKjHc&dbName=labplanet&actionName=NEW_INCIDENT&incidentTitle=&incidentDetail=Hola%20Soporte,%20Estoy%20teniendo%20un%20problema%20y%20me%20gustar%C3%ADa%20que%20me%20ayud%C3%A1rais

**Comment by FranGomezVenegas** [comment]
Resuelto
