### ISSUE TITLE
Hay problemas para subir el tester DB_SCHEMACONFIG_SPEC_RESULTCHECK para el step 1005. La pantalla de testing-scripts parece estar bien configurada, pero a la hora de subirlo, aparece  NODB_SCHEMACONFIG_SPECQUAL_RULEFORMAT. 

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#688]
![image](https://user-images.githubusercontent.com/81186702/140316705-685738f9-e6c1-4622-a7ac-88344e771a7e.png)
![image](https://user-images.githubusercontent.com/81186702/140317050-3f75cb86-0ff2-4b56-be4a-b6a27c4789ec.png)

**Comment by Joelsn** [comment]
1005	true	"2021-11-04 12:57:56.138712"	"2021-11-04 13:11:12.2912"	"Testing for spec limits in Aguas Ejemplo"	"DB_SCHEMACONFIG_SPEC_RESULTCHECK"


Esta linea viene de la base de datos y podemos ver que se sube como DB_SCHEMACONFIG_SPEC_RESULTCHECK. Será un problema de la configuración del tester???

**Comment by FranGomezVenegas** [comment]
Corregido
