### ISSUE TITLE
TDD Proc-deploy script 1005 step 32-33-34-35 Carbono organico total nos acepta valores negativos, ¿Puede haber valores negativos? 

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#689]
![image](https://user-images.githubusercontent.com/81186702/140504482-fe0dc5cf-486b-4dc0-8891-7b708c2f6a0e.png)

**Comment by Joelsn** [comment]
una segunda question, en tests que no se aceptan ni valores negativos ni valores con decimales, ¿Es correcto asignar el Code como ValueNoNumeric?

**Comment by FranGomezVenegas** [comment]
![image](https://user-images.githubusercontent.com/26067165/140515545-4070502b-0eab-4468-ab6c-99bad577f156.png)
No está definido un valor minimo permitido, lo añado para que lo testees.

A la pregunta de arriba, No. valueNotNumeric solo aplica si añades un valor estrictamente no numérico. El resto debe tener su código propio
