### ISSUE TITLE
Al reabrir incidencias podría salir el diálogo con las incidencias que se han cerrado en ese día.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#696]

**Comment by FranGomezVenegas** [comment]
Creado endpoint CLOSED_INCIDENTS_LAST_N_DAYS, si no recibe el argumento numDays entonces establece el periodo en los últimos 7 dias.

**Comment by FranGomezVenegas** [comment]
Track it in https://github.com/FranGomezVenegas/FETR/issues/41
