### ISSUE TITLE
Proc-Deploy Test 11, Parece que hay varios EndPoints que no están declarados y no permite realizar el Test Regresivo. Habría que hacer una lista de todos los que no están declarados?

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#700]
{"message_en":"The procedure proc-deploy has not declared as to allow performing those actions than the script 11 includes: [Step 2, Action:CANCELSAMPLE, Step 3, Action:UNCANCELSAMPLE, Step 8, Action:CANCELTEST, Step 9, Action:UNCANCELTEST, Step 10, Action:GET_SAMPLE_INFO, Step 11, Action:GET_SAMPLE_RESULTS]","is_error":true,"diagnostic":"LABPLANET_FALSE","message":"regressionTesting_actionsNotAllowedOrDeclaredAsPartOfThisProcedure","message_es":"El proceso proc-deploy no tiene declaradas acciones que el guion de pruebas 11 incluye: [Step 2, Action:CANCELSAMPLE, Step 3, Action:UNCANCELSAMPLE, Step 8, Action:CANCELTEST, Step 9, Action:UNCANCELTEST, Step 10, Action:GET_SAMPLE_INFO, Step 11, Action:GET_SAMPLE_RESULTS]"}

**Comment by FranGomezVenegas** [comment]
Los que menciona el mensaje ya son los que no están declarados. Claro que el cliente si sabrá cuales están declarados porque los declara él ... pero por ahora creo que es suficiente con este mensaje .... cuando ejecutes lo de coverage entonces tendrás info alineada con esta pregunta ...
