### ISSUE TITLE
Una foto de los problemas que se encuentran en los BDD y TDD de EM-DEMO-A

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#701]
![image](https://user-images.githubusercontent.com/81186702/141149390-7295af2c-96dc-4862-b3b5-3cec7cb5357c.png)

**Comment by FranGomezVenegas** [comment]
Los success para "los SamplingDate family" son:
![image](https://user-images.githubusercontent.com/26067165/141616564-826e410d-f314-4588-80e0-20d86c1b9e9d.png)

**Comment by Joelsn** [comment]
cierro porque se han cerrado en su mayoria!
