### ISSUE TITLE
Realizar una classEnvMon para habilitar production lot en los testings.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#705]

**Comment by Joelsn** [comment]
Nos da el mensaje que no encuentra ni el EndPoint de EM_NEW_PRODUCTION_LOT, EM_DEACTIVATE_PRODUCTION_LOT, EM_ACTIVATE_PRODUCTION_LOT.
![image](https://user-images.githubusercontent.com/81186702/142214544-207f45c8-e7b0-4b3e-a75e-cd93bf82352f.png)
![image](https://user-images.githubusercontent.com/81186702/142214819-516a9341-0651-4c60-bf84-cdfad161cdea.png)

**Comment by Joelsn** [comment]
valido! funciona perfectamente!!! GOODJOB!!!!!!!!!

**Comment by FranGomezVenegas** [comment]
Esoooooo

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
