### ISSUE TITLE
En el viejo FE, no funciona el botón "move to previous" Mahdii me dijo de si lo hacía y le comenté que igual era mejor hacer la pantalla de PlateReading y sus botones mientras se arreglaba esta incidencia, en el comentario dejo la respuesta de la API

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#706]
{"message_en":"","is_error":true,"diagnostic":"LABPLANET_FALSE","message":"Mandatory fields auditReasonPhrase,  not found in this request.","message_es":""}

**Comment by FranGomezVenegas** [comment]
El problema es que el credential dialog debe incluir la justification phrase ... y el valor debe ser pasado al endpoint en el argumento auditReasonPhrase

**Comment by FranGomezVenegas** [comment]
Si falla en la plataforma vieja no pasa nada, mientras funcione bien en la nueva ... ;)

**Comment by Joelsn** [comment]
cierro porque se ha comprobado que funciona correctamente en el nuevo FE
