### ISSUE TITLE
Parecería que el endpoint Canceltest no acaba de estar bien definido en Proc-Deploy, UncancelTest si parece estar bien, ya que nos avisa de que solo puede actuar sobre un testcancelado.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#708]
![image](https://user-images.githubusercontent.com/81186702/142225449-5fdb9db5-c471-4168-8279-f9b9dc448c75.png)

![image](https://user-images.githubusercontent.com/81186702/142225355-d25b6a1d-d13d-40cf-90ee-c461b00d404d.png)

**Comment by FranGomezVenegas** [comment]
Si el test está revisado ya no se puede cancelar, el test debe estar en progreso o no iniciado, pero una vez revisado no se puede cancelar.

**Comment by Joelsn** [comment]
ahh!! valeee!! compruebo y valido!

**Comment by Joelsn** [comment]
![image](https://user-images.githubusercontent.com/81186702/142823945-dd824d06-3660-4967-a61d-98ee0262bfd1.png)
se comprueba antes de realizar el reviewtest y parece funcionar correctamente! cierro incidencia!
