### ISSUE TITLE
En proc-deploy Test 11 script 20-24, encontramos un problema con la entrada de resultados, nos permite entrar resultados a las 2 primeras pero después nos da falso alegando que no encuentra el sampleanalysisresult

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#710]
![image](https://user-images.githubusercontent.com/81186702/143605397-eaf68181-1090-48f9-9bef-5a879af08717.png)

**Comment by FranGomezVenegas** [comment]
sample, sample_analysis y sample_analysis_result son los 3 objetos. Si le pasas el sample_analysis (test_id) en vez del sample_analysis_result entonces estás actuando sobre otro objeto o mejor dicho, le estás entrando el resultado por numero de test y no corresponden. 
Es importante tener cuidado con esto, si el argumento es resultId entonces hay que obtener sample_analysis_result y no sample_analysis porque ambos existen en la devolución de la consulta pero corresponden a entidades distintas ... es como darle la comida del perro al gato porque vivan juntos.... cada uno su comida, supongo.

![image](https://user-images.githubusercontent.com/26067165/145075240-a77134ab-f4de-4c7c-825c-4c73523a10db.png)

![image](https://user-images.githubusercontent.com/26067165/145075047-8ce92518-0828-4447-93e9-4c1b4c838b1b.png)

**Comment by FranGomezVenegas** [comment]
Corregido y funciona

![image](https://user-images.githubusercontent.com/26067165/145076218-ba7d43d8-94dc-4964-ba9c-c5fc0e129616.png)

![image](https://user-images.githubusercontent.com/26067165/145076280-32937b53-4f88-49c3-b6a5-9af673915060.png)

**Comment by Joelsn** [comment]
perfecto ya comprobado y cierro incidencia!
