### ISSUE TITLE
fieldName y fieldValue no debe permitir los campos de "description" y "2" como válidos.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#711]
![image](https://user-images.githubusercontent.com/81186702/143610688-f14eb053-425b-4d94-a133-78dbabfa036a.png)

**Comment by FranGomezVenegas** [comment]
Ahora mismo 'se lo comía', pero se va a reemplzar la linea actual (en gris) por devolver este error de formato.
![image](https://user-images.githubusercontent.com/26067165/143902156-dedc5855-9add-4a9a-9fef-69dfc54c238b.png)

**Comment by FranGomezVenegas** [comment]
Ejemplo aplicado:

Syntaxis:LABPLANET_FALSE. Code:objectOfArray_wrongFormat. Message:Wrong format in posic 0, value 2. It should be two values in the way of VALUE*BOOLEAN.

![image](https://user-images.githubusercontent.com/26067165/143902934-20b102e7-c508-4fbc-8a74-9984cd1bfc1a.png)
