### ISSUE TITLE
Hay que revisar los limites de Aire, en el test 1005 de em-demo-a podemos ver que acepta como IN el primer valor que ya debería contar como IN/Out, dejo un ejemplo.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#713]
![image](https://user-images.githubusercontent.com/81186702/143938328-0dd96944-6278-4aac-b7a1-9fb257f57633.png)
![image](https://user-images.githubusercontent.com/81186702/143938749-a3a53609-966c-4d8a-b3de-2f8ed00931f6.png)

**Comment by FranGomezVenegas** [comment]
Cierto ... más que un bug es un 'saber lo que queremos' .... 
![image](https://user-images.githubusercontent.com/26067165/144833301-cc9fcb7a-29e4-4ad4-8342-65e296988b15.png)
Para cumplir con lo que dice el texto, es decir, que el 25 no se considere IN entonces hay que crear el limite de control como MAXCONTROLSTRICT, lo añado y entonces ahora es así como es evaluado:
![image](https://user-images.githubusercontent.com/26067165/144833526-413f1e15-236b-4271-9c44-221aa66e3f0a.png)

Conclusión: Esto del STRICT es interesante pero muy sensible, por eso que es importante que los clientes creen estos TDD y asegurar que lo han configurado como necesitan. Cuando tengamos el 'tester' de limites que queremos añadir a la pantalla programas espero que esta parte esté mejor cubierta ... al igual que cuando podamos crear los tests en una interfaz gráfica y podamos obtener los nombre de analisis (y evitar lo de si es AireActivo con o sin espacio etc...) en vez de escribirlos pues también ... poco a poco ... ;)

**Comment by Joelsn** [comment]
Okey , según lo entiendo se ha añadido un nuevo limite (MAXCONTROLSTRICT) para el caso específico entre el In y el Out, debo entonces validar todos estos valores como MAXCONTROLSTRICT?

**Comment by FranGomezVenegas** [comment]
Los STRICT para cada max y min ya existían, se ha aplicado por primera vez a este programa. Sólo se ha añadido a este caso, si se quiere aplicar a todos se debería aplicar a cada uno porque aplicarlo para uno no significa aplicarlo a todos, son individuales e independientes.
