### ISSUE TITLE
Monitoring properties and db logs

### ISSUE THREAD

**Issue by FranGomezVenegas** [FranGomezVenegas/LP#714]
Te lo asigno en cuanto a que necesito que cada viernes me recuerdes de lanzar esto y ver qué hay para evitar que se acumule mucho y sea dificil de entender el contenido ¿vale?
Ahora mismo la frecuencia debería ser semanal pero en cuanto el contenido vemos que sea pequeño incrementaremos la frecuencia para ser cada 2 semanas, despues una al mes etc ...

El objetivo final no es tanto que no haya nada aqui (claro que si, esto es lo que debe suceder) sino más bien el hecho de ir monitoreando que no se vaya acumulando mucho.

A día de hoy ya he conseguido que con los tests de aire y agua no se genere nada en properties .... voy a continuar con db ...
![image](https://user-images.githubusercontent.com/26067165/144841053-5c9f9c6e-0178-4739-b43a-0e43657d71a1.png)

**Comment by Joelsn** [comment]
okey perfecto!!
