### ISSUE TITLE
Script 4 Step 11- 24, Hay que revisar porque en test regresivos de proc-deploy nos está devolviendo el code: DataSampleRevision_notReadyForRevision en reviewtest, este test tiene activado el autoapprove, pero si vamos al script 11 vemos que nos devuelveDataSample_SampleAnalysisCanceled (sin autoapprove)

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#715]

**Comment by FranGomezVenegas** [comment]
Resuelto, ahora falla un REVIEWSAMPLE pero diría que es correcto, creo que necesita un token alternativo y, además, en este momento la muestra aún no está revisada con lo que este step o el anterior es el que debe revisar la muestra, si se provee un token alternativo
