### ISSUE TITLE
Al firmar una auditoría de una muestra, falta el segundo nivel de childrens y no aparecen para firmar en el FE

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#716]
![image](https://user-images.githubusercontent.com/81186702/145610586-0373256b-bf43-4aed-9d9c-be7cc79c22ba.png)

**Comment by FranGomezVenegas** [comment]
Corregido!
La cuestión es que se tienen que vincular al primer id de audit porque ese es el que genera la acción principal, pero tiene que tomar el último para montar el action name. Antes tomaba el último id para ambas cosas y por eso perdía la trazabilidad respecto a la acción principal.

**Comment by Joelsn** [comment]
perfecto, he creado nuevas muestras y veo que si que funciona como debería! grande!
