### ISSUE TITLE
En el proceso de ProcDeploy hay un problema con LogSample, ni en el testregresivo ni en el FE nos está devolviendo respuesta.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#717]

**Comment by Joelsn** [comment]
Function code nos devuelve: Program <*1*> or location <*2*> not found for procedure <*3*>

Parece que no existe el programa o la location

**Comment by FranGomezVenegas** [comment]
Cierto, las mejoras de audit no se aplicaron al agua ... ya aplicado!
