### ISSUE TITLE
En el nuevo FE hay que mirar porque en la pantalla de identificación de microorganismos Nos permite mover la muestra a la siguiente pantalla aunque sea Out, solo debería permitirnos mover la muestra en caso de que sea In pero tenga alguna identificación

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#719]

**Comment by FranGomezVenegas** [comment]
Este es el tipico requerimiento que nos pedirá el usuario cuando toque, ahora mismo el template lo permite y si un cliente no quiere que lo permita entonces lo pedirá y se hará, es fácil y no hay problema en hacerlo, pero ahora no toca
