### ISSUE TITLE
Regresive Test DB_PLATFORM_INSTRUMENTS,=4 El sistema no debe permitir introducir dos valores de ENTER_EVENT_RESULT iguales, sino que debería pedir el endpoint ¿REENTER_EVENT_RESULTS?

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#726]
![image](https://user-images.githubusercontent.com/81186702/151176638-a0998bfc-60c2-4385-96c4-79d5962e5b3e.png)

Link del caso en concreto:
http://51.75.202.142:8888/LabPLANET-API/testing/platform/TestingRegressionUAT?procInstanceName=app-proc&scriptId=4&finalToken=eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hLCBhcHAtcHJvY10iLCJ0eXAiOiJKV1QiLCJhcHBTZXNzaW9uSWQiOiIxOTA5OCIsImFwcFNlc3Npb25TdGFydGVkRGF0ZSI6Ik1vbiBEZWMgMjAgMjM6Mjg6NDQgQ0VUIDIwMjEiLCJ1c2VyUm9sZSI6ImNvb3JkaW5hdG9yIiwiYWxnIjoiSFMyNTYiLCJpbnRlcm5hbFVzZXJJRCI6IjEyIn0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.g21aQ1WlsDWq5qh79lXnPKh_s3Ekv1RMYwhueQiiISQ&dbName=labplanet

**Comment by FranGomezVenegas** [comment]
Implementado

**Comment by Joelsn** [comment]
perfecto!!
