### ISSUE TITLE
En test regresivo de Instrumentos, se debe crear Endpoint de ReenterResults para que aplique a ENTER_EVENT_RESULT y Endpoint para reabrir en caso de openCalibration y OPEN_PREV_MAINT y su respectiva pareja para volver a cerrarlas

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#727]

**Comment by FranGomezVenegas** [comment]
Añadidas acciones: ENTER_EVENT_RESULT  y REOPEN_EVENT (el argumento es el eventId)

**Comment by Joelsn** [comment]
http://51.75.202.142:8888/LabPLANET-API/testing/platform/TestingRegressionUAT?procInstanceName=app-proc&scriptId=3&finalToken=eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hLCBhcHAtcHJvY10iLCJ0eXAiOiJKV1QiLCJhcHBTZXNzaW9uSWQiOiIxOTA5OCIsImFwcFNlc3Npb25TdGFydGVkRGF0ZSI6Ik1vbiBEZWMgMjAgMjM6Mjg6NDQgQ0VUIDIwMjEiLCJ1c2VyUm9sZSI6ImNvb3JkaW5hdG9yIiwiYWxnIjoiSFMyNTYiLCJpbnRlcm5hbFVzZXJJRCI6IjEyIn0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.g21aQ1WlsDWq5qh79lXnPKh_s3Ekv1RMYwhueQiiISQ&dbName=labplanet

Aplicados en el test 3, hace falta dar de alta estas acciones en app-proc

"El proceso app-proc no tiene declaradas acciones que el guion de pruebas 3 incluye: [Step 22, Action:, Step 23, Action:REENTER_EVENT_RESULT]"

**Comment by Joelsn** [comment]
aplicado y funciona correctamente!
