### ISSUE TITLE
Se han encontrado 2 errores de comportamiento en Identificación de Microorganismos:

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#729]
1. Al realizar una lectura de placas con resultado Out (5), la muestra a pasado a Identificación de Microorganismos de personal repetida 2 veces:
![image](https://user-images.githubusercontent.com/81186702/152033637-bb435bf6-1bad-4585-863a-2e6b99a3ecfb.png)

2. La muestra  2034 ha dado resultado inAlertMax pero no pasa ha pasado a identificación de microorganismos, pareciese que solo estén pasando a la Identificación de microorganismos las muestras con resultado Out.

Request Caso 1:
http://51.75.202.142:8888/LabPLANET-API/moduleenvmon/frontend/EnvMonSampleAPIfrontend?procInstanceName=em-demo-a&sampleFieldToRetrieve=sample_id%7Ccurrent_stage%7Cstatus%7Cstatus_previous%7Csampling_comment%7Csample_config_code%7Cprogram_name%7Clocation_name%7Cspec_code%7Cspec_variation_name&whereFieldsValue=MicroorganismIdentification%7Cprog_pers_template&whereFieldsName=current_stage%7Csample_config_code+in*&finalToken=eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hLCBhcHAtcHJvY10iLCJ0eXAiOiJKV1QiLCJhcHBTZXNzaW9uSWQiOiIxOTY0MSIsImFwcFNlc3Npb25TdGFydGVkRGF0ZSI6IlR1ZSBGZWIgMDEgMTY6NDE6MjggVVRDIDIwMjIiLCJ1c2VyUm9sZSI6ImNvb3JkaW5hdG9yIiwiYWxnIjoiSFMyNTYiLCJpbnRlcm5hbFVzZXJJRCI6IjEyIn0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.SCRGiW_6F2cv16C34_9dEdgDtdljwWyPukK2tJA3D_A&dbName=labplanet&actionName=GET_SAMPLE_MICROORGANISM_VIEW&userToCheck=marc&passwordToCheck=&esignPhraseToCheck=

Request Caso 2:
http://51.75.202.142:8888/LabPLANET-API/moduleenvmon/frontend/EnvMonSampleAPIfrontend?procInstanceName=em-demo-a&sampleFieldToRetrieve=sample_id%7Cprogram_name%7Clocation_name%7Ccurrent_stage%7Cstatus%7Csampling_date%7Csampling_comment%7Cincubation_batch%7Cincubation_incubator%7Cincubation_start%7Cincubation_end%7Cincubation2_batch%7Cincubation2_incubator%7Cincubation2_start%7Cincubation2_end%7Csample_config_code&whereFieldsValue=PlateReading%7Cprog_pers_template&whereFieldsName=current_stage%7Csample_config_code+not+in*&finalToken=eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hLCBhcHAtcHJvY10iLCJ0eXAiOiJKV1QiLCJhcHBTZXNzaW9uSWQiOiIxOTY0MSIsImFwcFNlc3Npb25TdGFydGVkRGF0ZSI6IlR1ZSBGZWIgMDEgMTY6NDE6MjggVVRDIDIwMjIiLCJ1c2VyUm9sZSI6ImNvb3JkaW5hdG9yIiwiYWxnIjoiSFMyNTYiLCJpbnRlcm5hbFVzZXJJRCI6IjEyIn0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.SCRGiW_6F2cv16C34_9dEdgDtdljwWyPukK2tJA3D_A&dbName=labplanet&actionName=SAMPLES_BY_STAGE&sampleId=2034&userToCheck=marc&passwordToCheck=&esignPhraseToCheck=

**Comment by FranGomezVenegas** [comment]
Caso 1 resuelto

**Comment by FranGomezVenegas** [comment]
Caso 2 tb resuelto. El problema es que ahora el field updated the sample audit es un json tb. Lo que me extraña es que no haya sido detectado antes.

**Comment by Joelsn** [comment]
perfecto, solucionado!
