### ISSUE TITLE
En el test nº8 de Aire, encontramos un caso de acción que no nos devuelve mensaje. Cuando realizamos un movetonext despues de asignar una incubadora a una tanda, provoca que el test se rompa.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#754]
![imagen](https://user-images.githubusercontent.com/81186702/158372472-d6618f5b-7f79-4fd9-a7e1-e2ea7f8a23f0.png)

Este caso se produce independientemente de tener la sintaxy en true or false.

**Comment by FranGomezVenegas** [comment]
Necesito detalles, en qué step sucede? en este test hay muchos "moveto" ...

**Comment by Joelsn** [comment]
a partir de la última mejora no se ha vuelto a producir este error, cierro la incidencia.
