### ISSUE TITLE
El sistema no debe permitir mover una muestra de pantalla cuando la muestra está dentro de una tanda. Esto lo podemos ver en el test script 8  step 6.(esta acción no es bloqueante)

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#755]

**Comment by Joelsn** [comment]
El sistema está permitiendo el siguiente ejemplo: 
1.se añade una muestra a una tanda
2.nos permite mover la muestra al paso anterior (cosa que no debería)
3.Empezar la incubación con la muestra en el paso anterior

Se espera que al bloquear la muestra y no poder moverla cuando esté dentro de una tanda, esto se arreglará.
![imagen](https://user-images.githubusercontent.com/81186702/158821891-8bc0375a-99d0-426a-b1fd-2f054bd2e98c.png)

**Comment by FranGomezVenegas** [comment]
![imagen](https://user-images.githubusercontent.com/26067165/159190820-dd489324-244f-4096-ba19-fe2a2b52645a.png)

**Comment by Joelsn** [comment]
perfect!
