### ISSUE TITLE
FE - Proc-Deploy, se encuentra problemas con Logsample, Enter Results, Review Sample y Programs. Las pantallas no se cargan.

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#758]

**Comment by Joelsn** [comment]
Urls de consultas:
Logsample:
http://51.75.202.142:8888/LabPLANET-API/moduleenvmon/frontend/EnvMonAPIfrontend?procInstanceName=proc-deploy&finalToken=eyJ1c2VyREIiOiJ3YXRlciIsImVTaWduIjoiZWxvY28iLCJ1c2VyREJQYXNzd29yZCI6ImxvY28iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbcHJvYy1kZXBsb3ldIiwidHlwIjoiSldUIiwiYXBwU2Vzc2lvbklkIjoiMjA2NjciLCJhcHBTZXNzaW9uU3RhcnRlZERhdGUiOiJXZWQgTWFyIDE2IDE4OjE0OjMzIFVUQyAyMDIyIiwidXNlclJvbGUiOiJjb29yZGluYXRvciIsInVzZXJfcHJvY2VkdXJlX2hhc2hjb2RlcyI6InByb2MtZGVwbG95KjEqNjc4OSIsImFsZyI6IkhTMjU2IiwiaW50ZXJuYWxVc2VySUQiOiI5In0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.NcYLf8Ttp5_BmiEsS74mVhiS4jfBKfRlBbsAqX4mkdI&dbName=labplanet&actionName=PROGRAMS_LIST&userToCheck=water&passwordToCheck=&esignPhraseToCheck=&isForTesting=false

Enter Results:
http://51.75.202.142:8888/LabPLANET-API/moduleenvmon/frontend/EnvMonSampleAPIfrontend?procInstanceName=proc-deploy&sampleAnalysisResultFieldToRetrieve=result_id%7Canalysis%7Cmethod_name%7Cmethod_version%7Cparam_name%7Cparam_type%7Craw_value%7Cuom%7Cspec_eval%7Cspec_eval_detail%7Cstatus%7Cmin_val_allowed%7Cmin_allowed_strict%7Cmax_val_allowed%7Cmax_allowed_strict&sortFieldsName=test_id%7Cresult_id&sampleAnalysisWhereFieldsName=testing_group%7Cstatus+not+in&sampleAnalysisWhereFieldsValue=FQ%7CREVIEWED*String&finalToken=eyJ1c2VyREIiOiJ3YXRlciIsImVTaWduIjoiZWxvY28iLCJ1c2VyREJQYXNzd29yZCI6ImxvY28iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbcHJvYy1kZXBsb3ldIiwidHlwIjoiSldUIiwiYXBwU2Vzc2lvbklkIjoiMjA2NjciLCJhcHBTZXNzaW9uU3RhcnRlZERhdGUiOiJXZWQgTWFyIDE2IDE4OjE0OjMzIFVUQyAyMDIyIiwidXNlclJvbGUiOiJjb29yZGluYXRvciIsInVzZXJfcHJvY2VkdXJlX2hhc2hjb2RlcyI6InByb2MtZGVwbG95KjEqNjc4OSIsImFsZyI6IkhTMjU2IiwiaW50ZXJuYWxVc2VySUQiOiI5In0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.NcYLf8Ttp5_BmiEsS74mVhiS4jfBKfRlBbsAqX4mkdI&dbName=labplanet&actionName=GET_SAMPLE_ANALYSIS_RESULT_LIST&sampleId=365&userToCheck=water&passwordToCheck=&esignPhraseToCheck=&isForTesting=false

Review Sample:
http://51.75.202.142:8888/LabPLANET-API/moduleenvmon/frontend/EnvMonSampleAPIfrontend?procInstanceName=proc-deploy&finalToken=eyJ1c2VyREIiOiJ3YXRlciIsImVTaWduIjoiZWxvY28iLCJ1c2VyREJQYXNzd29yZCI6ImxvY28iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbcHJvYy1kZXBsb3ldIiwidHlwIjoiSldUIiwiYXBwU2Vzc2lvbklkIjoiMjA2NjciLCJhcHBTZXNzaW9uU3RhcnRlZERhdGUiOiJXZWQgTWFyIDE2IDE4OjE0OjMzIFVUQyAyMDIyIiwidXNlclJvbGUiOiJjb29yZGluYXRvciIsInVzZXJfcHJvY2VkdXJlX2hhc2hjb2RlcyI6InByb2MtZGVwbG95KjEqNjc4OSIsImFsZyI6IkhTMjU2IiwiaW50ZXJuYWxVc2VySUQiOiI5In0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.NcYLf8Ttp5_BmiEsS74mVhiS4jfBKfRlBbsAqX4mkdI&dbName=labplanet&actionName=GET_SAMPLE_ANALYSIS_RESULT_LIST&sampleId=349&userToCheck=water&passwordToCheck=&esignPhraseToCheck=&isForTesting=false

**Comment by Joelsn** [comment]
Se ha revisado y sigue fallando Logsample y programs, yo creo que viene de la pantalla de programs porque está bloqueada directamente, consulta de logsample:

http://51.75.202.142:8888/LabPLANET-API/moduleenvmon/frontend/EnvMonAPIfrontend?procInstanceName=proc-deploy&finalToken=eyJ1c2VyREIiOiJ3YXRlciIsImVTaWduIjoiZWxvY28iLCJ1c2VyREJQYXNzd29yZCI6ImxvY28iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbcHJvYy1kZXBsb3ldIiwidHlwIjoiSldUIiwiYXBwU2Vzc2lvbklkIjoiMjA2NzkiLCJhcHBTZXNzaW9uU3RhcnRlZERhdGUiOiJUaHUgTWFyIDE3IDExOjU0OjQzIFVUQyAyMDIyIiwidXNlclJvbGUiOiJjb29yZGluYXRvciIsInVzZXJfcHJvY2VkdXJlX2hhc2hjb2RlcyI6InByb2MtZGVwbG95KjEqNjc4OSIsImFsZyI6IkhTMjU2IiwiaW50ZXJuYWxVc2VySUQiOiI5In0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.QaLKqvGfiBoCzWDsdq4Hp-pN90DcRFzLnQX7a06_rHk&dbName=labplanet&actionName=PROGRAMS_LIST&userToCheck=water&passwordToCheck=&esignPhraseToCheck=&isForTesting=false

**Comment by FranGomezVenegas** [comment]
las lineas que aparecen en log samples son información del programa, con lo cual si falla programs entonces en consecuencia tb fall logSamples ...

**Comment by FranGomezVenegas** [comment]
El problema es que el segundo programa es un 'fake' para pruebas, no tiene toda la información y por eso hacía fallar a la consulta ... pero ahora la consulta 'es más fuerte' para no fallar si esto sucede

**Comment by Joelsn** [comment]
okey! revisado y ahora funciona programs y se puede ver los diferentes programas:
 
![imagen](https://user-images.githubusercontent.com/81186702/158828375-d31d2fc9-e120-4655-a661-cb5498df90cd.png)
