### ISSUE TITLE
Al realizar SamplePlateReading/Reenterresult fuera de limite, se genera una desviación correctamente, pero no avanza a Identificación de microorganismos

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#778]

**Comment by FranGomezVenegas** [comment]
no es que se cree , es que no se mueve a microorganism, en todo caso

**Comment by FranGomezVenegas** [comment]
Había que añadir la acción a la lista de acciones como (RE)ENTER_PLATE_READING en la regla sampleStagesActionAutoMoveToNext ... para indicarle al BE que estas acciones deben 'disparar' la evaluación de si debe moverse a siguiente etapa o no, la muestra.
![imagen](https://user-images.githubusercontent.com/26067165/166587594-471e5ab1-c6d9-4209-b7ce-45e5ef1549d8.png)

**Comment by Joelsn** [comment]
Se ha comprobado y las muestras pasan correctamente a identificación de microorganismos, pero no van a Desviaciones, voy a cerrar esta Incidencia y crearé una nueva.
![imagen](https://user-images.githubusercontent.com/81186702/166647080-1272eef6-6eb8-4017-a452-2810ed402164.png)
