### ISSUE TITLE
Instrument Managment - FE - El endpoint Start Service no parece estar declarado

### ISSUE THREAD

**Issue by Joelsn** [FranGomezVenegas/LP#779]
http://51.75.202.142:8888/LabPLANET-API/app/procs/InstrumentsAPIactions?procInstanceName=app-proc&instrumentName=demoJ&finalToken=eyJ1c2VyREIiOiJtYXJjIiwiZVNpZ24iOiJsb2NvbyIsInVzZXJEQlBhc3N3b3JkIjoiYXVsaW4iLCJkYk5hbWUiOiJsYWJwbGFuZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbZW0tZGVtby1hLCBhcHAtcHJvYywgYXBwXSIsInR5cCI6IkpXVCIsImFwcFNlc3Npb25JZCI6IjIxMDY4IiwiYXBwU2Vzc2lvblN0YXJ0ZWREYXRlIjoiVGh1IEFwciAwNyAxMzo1MDo1MyBVVEMgMjAyMiIsInVzZXJSb2xlIjoiY29vcmRpbmF0b3IiLCJ1c2VyX3Byb2NlZHVyZV9oYXNoY29kZXMiOiJlbS1kZW1vLWEqMSoxODIzMTQ3NTAyfGFwcC1wcm9jKjEqfGFwcCoxKjExMSIsImFsZyI6IkhTMjU2IiwiaW50ZXJuYWxVc2VySUQiOiIxMiJ9.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.oApEj302bwmSopZAuGKReLGB_t3Jr7tSP6PR7Ep1q8k&dbName=labplanet&actionName=START_SERVICE&userToCheck=marc&passwordToCheck=&esignPhraseToCheck=&isForTesting=false

**Comment by FranGomezVenegas** [comment]
No existe ... pero debería ;)

**Comment by Joelsn** [comment]
Funciona correctamente, sólo faltaría añadir un mensaje de success 

![imagen](https://user-images.githubusercontent.com/81186702/162912222-14d7ac87-1e21-4a39-afe6-c20c7b046dcb.png)
![imagen](https://user-images.githubusercontent.com/81186702/162917870-4a51cd62-78b4-4687-8a6a-aa2567773670.png)

**Comment by FranGomezVenegas** [comment]
Hecho!
